/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;


import Controlador.ControladorDespesa;
import Modelo.ModeloTabelas;
import Modelo.clsDespesa;
import giovanellis.SqlServer;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Alex
 */
public class frmCadastrarDespesa extends javax.swing.JFrame {
    private ControladorDespesa DAO;
     private clsDespesa objDespesa;
     private clsDespesa objDespAtua;
   SqlServer conecta = new SqlServer();
   public int metodo;
   
    SqlServer connCombo = new SqlServer();
   

   
    public frmCadastrarDespesa() throws Exception {
        
         initComponents();
         this.setIconImage(new ImageIcon(getClass().getResource("/giovanellis/Icone.png")).getImage());  
         DAO = new ControladorDespesa();
         conecta.getCon();
         
           preencherTabela("Select * from TipoDespesa order by NomeDespesa" );
         PreencherCombobox();
         rdTodas.setSelected(true);
          
         
         
         
        
        
    }
    
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoCadastro = new javax.swing.ButtonGroup();
        GrupoDespesas = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        lblCadastro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        lblAltera = new javax.swing.JLabel();
        CmbDespesa = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnAtualiza = new javax.swing.JButton();
        txtSituação = new javax.swing.JTextField();
        txtCodigoDespesa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Novadespesa = new javax.swing.JTextField();
        rdTodas = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        btnAlterar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Despesas Cadastradas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 22, 420, -1));

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 509, 178));

        lblCadastro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastro.setText("Cadastramento de Despesas:");
        getContentPane().add(lblCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 273, -1));

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, -1, -1));

        lblAltera.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAltera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAltera.setText("Alteração de Despesa:");
        getContentPane().add(lblAltera, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 221, -1));

        CmbDespesa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));
        CmbDespesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CmbDespesaMouseClicked(evt);
            }
        });
        CmbDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbDespesaActionPerformed(evt);
            }
        });
        getContentPane().add(CmbDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 184, -1));

        GrupoCadastro.add(jRadioButton1);
        jRadioButton1.setText("Ativo");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, -1, -1));

        GrupoCadastro.add(jRadioButton2);
        jRadioButton2.setText("Inativo");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, -1, -1));

        btnAtualiza.setText("Atualizar");
        btnAtualiza.setEnabled(false);
        btnAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, -1, -1));

        txtSituação.setEnabled(false);
        getContentPane().add(txtSituação, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 94, -1));

        txtCodigoDespesa.setEnabled(false);
        getContentPane().add(txtCodigoDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 94, -1));

        jLabel3.setText("Código:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jLabel4.setText("Situação:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));
        getContentPane().add(txt_Novadespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 256, -1));

        GrupoDespesas.add(rdTodas);
        rdTodas.setText("Todas");
        rdTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTodasActionPerformed(evt);
            }
        });
        getContentPane().add(rdTodas, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 69, -1, -1));

        GrupoDespesas.add(jRadioButton3);
        jRadioButton3.setText("Inativas");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, -1, -1));

        GrupoDespesas.add(jRadioButton4);
        jRadioButton4.setText("Ativas");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 69, -1, -1));

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, -1, -1));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, -1, -1));

        setSize(new java.awt.Dimension(544, 686));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
         
        try{
           
    if(validarCampos()){
        
        if(PreencherObjeto()){
            if(DAO.Incluir(objDespesa)){
                
         JOptionPane.showMessageDialog(this, "Dados salvos com Sucesso");
         preencherTabela("Select * from TipoDespesa order by NomeDespesa" );
         PreencherCombobox();
            }
        }
    }
    else{
             JOptionPane.showMessageDialog(this, "Não foi possivel inserir os Dados");   
            }
          
        
      }catch(Exception erro)
      {
      JOptionPane.showMessageDialog(this,"Erro"+erro.getMessage());
      }
    
         LimpaCampos();
       
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblAltera.setVisible(false);
        jRadioButton1.setVisible(false);
      jRadioButton2.setVisible(false);    
      txt_Novadespesa.requestFocus();
      CmbDespesa.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void JTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableMouseClicked
  
      int linha_selecionada = JTable.getSelectedRow(); // Pega a linha selecionada.
      txtCodigoDespesa.setText(JTable.getValueAt(linha_selecionada, 0).toString());
      txt_Novadespesa.setText(JTable.getValueAt(linha_selecionada, 1).toString());
      txtSituação.setText(JTable.getValueAt(linha_selecionada, 2).toString());
      
      
    }//GEN-LAST:event_JTableMouseClicked

    private void btnAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizaActionPerformed
       
        try{
           
    if(validarCampos()){
        
        if(PreencherObjetoUp()){
            if(DAO.Editar(objDespesa)){
                
         JOptionPane.showMessageDialog(this, "Dados atualizados com Sucesso");
         preencherTabela("Select * from TipoDespesa order by NomeDespesa" );
         PreencherCombobox();
         jRadioButton1.setSelected(false);
         jRadioButton2.setSelected(false);
            }
        }
    }
    else{
             JOptionPane.showMessageDialog(this, "Não foi possivel atualizar os Dados");   
            }
          
        
      }catch(Exception erro)
      {
      JOptionPane.showMessageDialog(this,"Erro"+erro.getMessage());
      }
    
         
       
      
    LimpaCampos();
    
    }//GEN-LAST:event_btnAtualizaActionPerformed

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
       txtSituação.setText("Inativo");
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void CmbDespesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbDespesaMouseClicked
      int linha_selecionada = CmbDespesa.getSelectedIndex(); // Pega a linha selecionada.
      txtCodigoDespesa.setText(JTable.getValueAt(linha_selecionada, 0).toString());
      txt_Novadespesa.setText(JTable.getValueAt(linha_selecionada, 1).toString());
      txtSituação.setText(JTable.getValueAt(linha_selecionada, 2).toString()); 
    }//GEN-LAST:event_CmbDespesaMouseClicked

    private void CmbDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbDespesaActionPerformed
   
    }//GEN-LAST:event_CmbDespesaActionPerformed

    private void rdTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTodasActionPerformed
        preencherTabela("Select * from TipoDespesa order by NomeDespesa asc" );
        PreencherCombobox();
    }//GEN-LAST:event_rdTodasActionPerformed
    
    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
    preencherTabela("Select * from TipoDespesa where SituacaoDespesa = 'Inativo' order by NomeDespesa asc" );
    PreencherComboboxInativas();
    
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        preencherTabela("Select * from TipoDespesa where SituacaoDespesa = 'Ativo' order by NomeDespesa asc" );
        PreencherComboboxAtivas();
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        lblCadastro.setVisible(false);
        lblAltera.setVisible(true);
        btnAtualiza.setEnabled(true);
      btnCadastrar.setEnabled(false);
      jRadioButton1.setVisible(true);
      jRadioButton2.setVisible(true);
      CmbDespesa.setVisible(true);
        
        
        int linha_selecionada = CmbDespesa.getSelectedIndex(); // Pega a linha selecionada.
      txtCodigoDespesa.setText(JTable.getValueAt(linha_selecionada, 0).toString());
      txt_Novadespesa.setText(JTable.getValueAt(linha_selecionada, 1).toString());
      txtSituação.setText(JTable.getValueAt(linha_selecionada, 2).toString());
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      btnAtualiza.setEnabled(false);
      jRadioButton1.setVisible(false);
      jRadioButton2.setVisible(false);
      LimpaCampos();
      txt_Novadespesa.requestFocus();
      btnCadastrar.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
    txtSituação.setText("Ativo");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
     txtSituação.setText("Inativo");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmCadastrarDespesa().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frmCadastrarDespesa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CmbDespesa;
    private javax.swing.ButtonGroup GrupoCadastro;
    private javax.swing.ButtonGroup GrupoDespesas;
    private javax.swing.JTable JTable;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAtualiza;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAltera;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JRadioButton rdTodas;
    private javax.swing.JTextField txtCodigoDespesa;
    private javax.swing.JTextField txtSituação;
    private javax.swing.JTextField txt_Novadespesa;
    // End of variables declaration//GEN-END:variables


 

public void LimpaCampos()
{
txtCodigoDespesa.setText("");
txtSituação.setText("");
txt_Novadespesa.setText("");
jRadioButton1.setSelected(false);
jRadioButton2.setSelected(false);

}

public boolean validarCampos()
{
if (txt_Novadespesa.getText().equals("")){	
    JOptionPane.showMessageDialog(this, "Preencha o campo Despesa");
   txt_Novadespesa.requestFocus();
   return false;
}


return true;

}


public boolean PreencherObjeto()
{
objDespesa = new clsDespesa();
objDespesa.setNomeDespesa(txt_Novadespesa.getText());


//objDespesa.setCodigo(Integer.parseInt(txtCodigo.getText());// Código para pegar Inteiros.
 
return true;
}

public boolean PreencherObjetoUp()
{
objDespesa = new clsDespesa();
objDespesa.setNomeDespesa(txt_Novadespesa.getText());
objDespesa.setCodDespesa(Integer.parseInt(txtCodigoDespesa.getText()));// Código para pegar Inteiros.
objDespesa.setSituacaoDespesa(txtSituação.getText());
 
return true;
}

public boolean UpdateObjeto()
{
objDespesa = new clsDespesa();
objDespesa.setNomeDespesa(txt_Novadespesa.getText());




//objDespesa.setCodigo(Integer.parseInt(txtCodigo.getText());// Código para pegar Inteiros.
 
return true;
}


   public void preencherTabela(String Sql){
    ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"Código","Nome da Despesa","Situação"};
    
    conecta.executaSql(Sql);
    try{
        conecta.rs.first();
        do{
    dados.add(new Object[]{conecta.rs.getInt("codTipoDespesa"),conecta.rs.getString("NomeDespesa"),conecta.rs.getString("SituacaoDespesa")});
          }while(conecta.rs.next());
        }
    catch(Exception e){
    JOptionPane.showMessageDialog(this,"Erro ao preencher o ArrayList");
    
    }
    
    ModeloTabelas modelo = new ModeloTabelas(dados, Colunas); //Instacia a classe do modelo da Tabela.
    JTable.setModel(modelo);
    JTable.getColumnModel().getColumn(0).setPreferredWidth(80); // Tamanho em pixel da coluna
    JTable.getColumnModel().getColumn(0).setResizable(false);
    JTable.getColumnModel().getColumn(1).setPreferredWidth(299);
    JTable.getColumnModel().getColumn(1).setResizable(false);
    JTable.getColumnModel().getColumn(2).setPreferredWidth(123);
    JTable.getColumnModel().getColumn(2).setResizable(false);
    JTable.getTableHeader().setReorderingAllowed(false);
    JTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);//Não pode ser redimensionada
    JTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
  

}



 public clsDespesa getDespesa()
    {
    clsDespesa Desp = new clsDespesa();
      if (!(txt_Novadespesa.getText().equals("")))
    {
    Desp.setCodDespesa(Integer.parseInt(txtCodigoDespesa.getText()));  
    }
    Desp.setNomeDespesa(txt_Novadespesa.getText());
    Desp.setSituacaoDespesa(txtSituação.getText());
  
    
    return Desp;
    }

 
public void PreencherCombobox(){
         connCombo.getCon();
         connCombo.executaSql("select NomeDespesa from TipoDespesa order by NomeDespesa");
         CmbDespesa.removeAllItems();
         try{
         connCombo.rs.first();
         do{
         CmbDespesa.addItem(connCombo.rs.getString("NomeDespesa"));
         
         }while(connCombo.rs.next());
         
         
         }catch(Exception e){
         JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ComboBox"+e);
         }



}

public void PreencherComboboxInativas(){
         connCombo.getCon();
         connCombo.executaSql("select NomeDespesa from TipoDespesa where SituacaoDespesa = 'Inativo' order by NomeDespesa");
         CmbDespesa.removeAllItems();
         try{
         connCombo.rs.first();
         do{
         CmbDespesa.addItem(connCombo.rs.getString("NomeDespesa"));
         
         }while(connCombo.rs.next());
         
         
         }catch(Exception e){
         JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ComboBox"+e);
         }



}

public void PreencherComboboxAtivas(){
         connCombo.getCon();
         connCombo.executaSql("select NomeDespesa from TipoDespesa where SituacaoDespesa = 'Ativo' order by NomeDespesa");
         CmbDespesa.removeAllItems();
         try{
         connCombo.rs.first();
         do{
         CmbDespesa.addItem(connCombo.rs.getString("NomeDespesa"));
         
         }while(connCombo.rs.next());
         
         
         }catch(Exception e){
         JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ComboBox"+e);
         }



}



 

}





