/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controlador.ControladorLancamentoDespesas;
import Modelo.ModeloTabelas;
import Modelo.clsLancamentoDespesas;
import java.util.Date;
import giovanellis.SqlServer;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Alex
 */
public class frmDespesas extends javax.swing.JFrame {
    private ControladorLancamentoDespesas DAO;
    private clsLancamentoDespesas ObjLancaDespesa;
    SqlServer conecta = new SqlServer();
     SqlServer connCombo = new SqlServer();
   
    
        
        
    
    public frmDespesas() throws Exception {
        SqlServer conn = new SqlServer();
         this.setIconImage(new ImageIcon(getClass().getResource("/giovanellis/Icone.png")).getImage());  
        initComponents();
        conecta.getCon();
        
         preencherTabela("Select * from TipoDespesa order by NomeDespesa" );
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodesp = new javax.swing.JTextField();
        jdtDatapagamento = new com.toedter.calendar.JDateChooser();
        Jdcfim = new com.toedter.calendar.JDateChooser();
        Jdcinicio = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jdtDatapagamento1 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        txtValor1 = new javax.swing.JTextField();
        CmbDespesa = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Despesas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome da Despesa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2.setText("Data de Vencimento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel6.setText("Valor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        getContentPane().add(txtCodesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 70, -1));
        getContentPane().add(jdtDatapagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 114, -1));

        Jdcfim.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JdcfimPropertyChange(evt);
            }
        });
        getContentPane().add(Jdcfim, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 140, -1));

        Jdcinicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JdcinicioPropertyChange(evt);
            }
        });
        getContentPane().add(Jdcinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 140, -1));

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 420, 106));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 80, -1));

        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        jButton4.setText("Lançar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Consulta de Lançamento de Despesas");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 420, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Água", "Luz", "Telefone", "Internet", "Aluguel", "Outros" }));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Lançamentos de Despesas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 420, -1));

        jLabel3.setText("Data de Pagamento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        getContentPane().add(jdtDatapagamento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 114, -1));

        jButton3.setText("Cancelar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));
        getContentPane().add(txtValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 70, -1));

        CmbDespesa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbDespesa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbDespesaItemStateChanged(evt);
            }
        });
        CmbDespesa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CmbDespesaFocusGained(evt);
            }
        });
        CmbDespesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CmbDespesaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CmbDespesaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CmbDespesaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CmbDespesaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CmbDespesaMouseReleased(evt);
            }
        });
        CmbDespesa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CmbDespesaPropertyChange(evt);
            }
        });
        getContentPane().add(CmbDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 100, -1));

        jMenu1.setText("Cadastrar Despesa");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(454, 593));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try {
                new frmHome().setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(frmDespesas.class.getName()).log(Level.SEVERE, null, ex);
            }
        dispose();
        timer.stop();;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      validarCampos();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    preencherTabela("select * from Pedido as P Inner join Detalhe_Pedido as DP On p.Cod_Pedido = DP.Cod_Pedido inner join Produto as Pro on Dp.Cod_Produto = Pro.Cod_Produto where  p.Data between '"+datainicio+"' and'"+datafim+"'");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       try {
                new frmCadastrarDespesa().setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(frmDespesas.class.getName()).log(Level.SEVERE, null, ex);
            }
        dispose();        
    }//GEN-LAST:event_jMenu1MouseClicked

    private void JTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableMouseClicked
      int linha_selecionada = JTable.getSelectedRow(); // Pega a linha selecionada.
      txtCodesp.setText(JTable.getValueAt(linha_selecionada, 0).toString());
    }//GEN-LAST:event_JTableMouseClicked

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    preencherCombo();
    }//GEN-LAST:event_formWindowOpened

    private void JdcinicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JdcinicioPropertyChange
     try{ 
        data1 = Jdcinicio.getDate();
        datainicio = formato.format (data(Jdcinicio.getDate()));
      System.out.println(datainicio);
      // data receba um formato e formate o método data e guarde na varíável e guarde na caixa de combinação
    
  
    }
    catch (Exception e){}
    }//GEN-LAST:event_JdcinicioPropertyChange

    private void JdcfimPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JdcfimPropertyChange
  try{ 
        data2 = Jdcfim.getDate();
        datafim = formato.format (data(Jdcfim.getDate()));
      System.out.println(datafim);
      // data receba um formato e formate o método data e guarde na varíável e guarde na caixa de combinação
    
  
    }
    catch (Exception e){}
    }//GEN-LAST:event_JdcfimPropertyChange

    private void CmbDespesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbDespesaMouseClicked
int linha_selecionada = CmbDespesa.getSelectedIndex(); // Pega a linha selecionada.
      txtCodesp.setText(JTable.getValueAt(linha_selecionada, 0).toString());
      int cod = Integer.parseInt(txtCodesp.getText());
      System.out.println(cod);
      preencherTabela("Select * from TipoDespesa order by NomeDespesa  where codTipoDespesa ="+cod);     
    }//GEN-LAST:event_CmbDespesaMouseClicked

    private void CmbDespesaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbDespesaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbDespesaMousePressed

    private void CmbDespesaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbDespesaMouseEntered
 
        //Funciona, mas tem que voltar o mouse
        
        //int linha_selecionada = CmbDespesa.getSelectedIndex(); // Pega a linha selecionada.
     // txtCodesp.setText(JTable.getValueAt(linha_selecionada, 0).toString());
    //  int cod = Integer.parseInt(txtCodesp.getText());
     // System.out.println(cod);
     // preencherTabela("Select * from TipoDespesa order by NomeDespesa  where codTipoDespesa ="+cod);
      //CmbDespesa.requestFocus();
    }//GEN-LAST:event_CmbDespesaMouseEntered

    private void CmbDespesaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbDespesaMouseExited
      
    }//GEN-LAST:event_CmbDespesaMouseExited

    private void CmbDespesaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbDespesaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbDespesaMouseReleased

    private void CmbDespesaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CmbDespesaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbDespesaPropertyChange

    private void CmbDespesaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbDespesaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbDespesaItemStateChanged

    private void CmbDespesaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CmbDespesaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbDespesaFocusGained

    /**
     * @param args the command line arguments
     */
    
    
    int contador = 20;
    
    public void escreva()
    {
        System.out.println(contador);
       
    }
 
    private javax.swing.Timer timer = new javax.swing.Timer(60*1000,new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent e)
        {
            escreva();
            contador--;
            if(contador == 0)
            {
              
                try {
                    new frmLogin().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frmDespesas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    });
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmDespesas().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frmDespesas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CmbDespesa;
    private javax.swing.JTable JTable;
    private com.toedter.calendar.JDateChooser Jdcfim;
    private com.toedter.calendar.JDateChooser Jdcinicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdtDatapagamento;
    private com.toedter.calendar.JDateChooser jdtDatapagamento1;
    private javax.swing.JTextField txtCodesp;
    private javax.swing.JTextField txtValor1;
    // End of variables declaration//GEN-END:variables
Date data1, data2;
String datainicio, datafim, data;


  public Date datas(Date i){ 
    // Método com retorno. Retorna data
        datainicio=formato.format(i);
        DateFormat df = DateFormat.getDateInstance
                (DateFormat.LONG, new Locale ("pt","BR"));
        
    //Cria um novo formatador para formatar as datas em formato longo escrito em português
    
        
                return i;
                
 }
     public Date data(Date f){ 
    // Método com retorno. Retorna data
        datafim=formato.format(f);
        DateFormat df = DateFormat.getDateInstance
                (DateFormat.LONG, new Locale ("pt","BR"));
        
    //Cria um novo formatador para formatar as datas em formato longo escrito em português
    
        
                return f;
                
 }
 
 
 
 SimpleDateFormat formato =
            new SimpleDateFormat("dd/MM/yyyy");
    //Define Formato de Data
    
 
public boolean validarCampos()
{
/*if (txtDespesa.getText().equals("")){	
    JOptionPane.showMessageDialog(this, "Preencha o campo Despesa");
   txtDespesa.requestFocus();
   return false;
}
if (txtValor.getText().equals("")){	
    JOptionPane.showMessageDialog(this, "Informe o Valor");
   txtValor.requestFocus();
   return false;
}
try{
if (jdtDatapagamento.getDate().equals("")){	
    JOptionPane.showMessageDialog(this, "Informe a data de Pagamento");
   txtDespesa.requestFocus();
   return false;
}}catch(Exception erro){JOptionPane.showMessageDialog(this,"Informe a Data");}
*/
return true;

}
public void preencherTabela(String Sql){
    ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"Código","Nome da Despesa","Situação"};
    
    conecta.executaSql(Sql);
    try{
        conecta.rs.first();
        do{
    dados.add(new Object[]{conecta.rs.getInt("codTipoDespesa"),conecta.rs.getString("NomeDespesa"),conecta.rs.getString("SituacaoDespesa")});
          }while(conecta.rs.next());
        }
    catch(Exception e){
    JOptionPane.showMessageDialog(this,"Erro ao preencher o ArrayList");
    
    }
    
    ModeloTabelas modelo = new ModeloTabelas(dados, Colunas); //Instacia a classe do modelo da Tabela.
    JTable.setModel(modelo);
    JTable.getColumnModel().getColumn(0).setPreferredWidth(80); // Tamanho em pixel da coluna
    JTable.getColumnModel().getColumn(0).setResizable(false);
    JTable.getColumnModel().getColumn(1).setPreferredWidth(299);
    JTable.getColumnModel().getColumn(1).setResizable(false);
    JTable.getColumnModel().getColumn(2).setPreferredWidth(123);
    JTable.getColumnModel().getColumn(2).setResizable(false);
    JTable.getTableHeader().setReorderingAllowed(false);
    JTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);//Não pode ser redimensionada
    JTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
  

}
public void preencherCombo()
{
         connCombo.getCon();
         connCombo.executaSql("select NomeDespesa from TipoDespesa where SituacaoDespesa = 'Ativo' order by NomeDespesa");
         CmbDespesa.removeAllItems();
         try{
         connCombo.rs.first();
         do{
         CmbDespesa.addItem(connCombo.rs.getString("NomeDespesa"));
         
         }while(connCombo.rs.next());
         
         
         }catch(Exception e){
         JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ComboBox"+e);
         }

}


}




