/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import giovanellis.SqlServer;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class frmFornecedores extends javax.swing.JFrame {
    SqlServer connCombo = new SqlServer();
    
    /**
     * Creates new form frmFornecedores
     */
    public frmFornecedores() throws Exception {
        
       
         this.setIconImage(new ImageIcon(getClass().getResource("/giovanellis/Icone.png")).getImage());  
        initComponents();
        
       //select * from Fornecedor as F inner join CompraFornecedor as Cf on Cf.Cod_Fornecedor = F.Cod_Fornecedor where Data_Venda between '17-07-2014' and '22-08-2014'
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JdcFim = new com.toedter.calendar.JDateChooser();
        JdcInicio = new com.toedter.calendar.JDateChooser();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTotal = new javax.swing.JButton();
        ComboFornecedores = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fornecedores");
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JdcFim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JdcFimMouseClicked(evt);
            }
        });
        JdcFim.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JdcFimPropertyChange(evt);
            }
        });
        getContentPane().add(JdcFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 130, -1));

        JdcInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JdcInicioMouseClicked(evt);
            }
        });
        JdcInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JdcInicioPropertyChange(evt);
            }
        });
        getContentPane().add(JdcInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 130, -1));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 70, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 100, 30));

        btnTotal.setText("Calcular");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
        getContentPane().add(btnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        ComboFornecedores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", " " }));
        getContentPane().add(ComboFornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 390, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome do Fornecedor", "Insumo Comprado", "Data do Pedido", "Valor do Pedido"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 640, 120));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Descritivos de Compras de Fornecedores");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 30));

        jLabel3.setText("Nome do Fornecedor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel4.setText("Data Inicial");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel5.setText("Data Final");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        setSize(new java.awt.Dimension(671, 524));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JdcFimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JdcFimMouseClicked
     
    }//GEN-LAST:event_JdcFimMouseClicked

    private void JdcInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JdcInicioMouseClicked
   
    }//GEN-LAST:event_JdcInicioMouseClicked

    private void JdcFimPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JdcFimPropertyChange
  try{ 
        
        datafim = formato.format (data(JdcFim.getDate()));
      System.out.println(datafim);
      // data receba um formato e formate o método data e guarde na varíável e guarde na caixa de combinação
    
  
    }
    catch (Exception e){}
    
    }//GEN-LAST:event_JdcFimPropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     PreencherCombobox();
    
    }//GEN-LAST:event_formWindowOpened

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        try {
            
        } catch (Exception ex) {
            Logger.getLogger(frmFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
       dispose();
       timer.stop();
 
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void JdcInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JdcInicioPropertyChange
      try{ 
        
        datainicio = formato.format (datas(JdcInicio.getDate()));
      System.out.println(datainicio);
      // data receba um formato e formate o método data e guarde na varíável e guarde na caixa de combinação
    
  
    }
    catch (Exception e){}
    }//GEN-LAST:event_JdcInicioPropertyChange

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        try{
          
        if((data1.getDate() - data2.getDate())>0 )  
        {
        
        JOptionPane.showMessageDialog(null, "Data Incorreta");
            
        }
        
        }catch(Exception e){}
            
    }//GEN-LAST:event_btnTotalActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
  
    }//GEN-LAST:event_formPropertyChange
    public Date datas(Date i){ 
    // Método com retorno. Retorna data
        datainicio=formato.format(i);
        DateFormat df = DateFormat.getDateInstance
                (DateFormat.LONG, new Locale ("pt","BR"));
        
    //Cria um novo formatador para formatar as datas em formato longo escrito em português
    
        
                return i;
                
 }
     public Date data(Date f){ 
    // Método com retorno. Retorna data
        datafim=formato.format(f);
        DateFormat df = DateFormat.getDateInstance
                (DateFormat.LONG, new Locale ("pt","BR"));
        
    //Cria um novo formatador para formatar as datas em formato longo escrito em português
    
        
                return f;
                
 }

 int contador = 20;
    
    public void escreva()
    {
        System.out.println(contador);
       
    }
 
    private javax.swing.Timer timer = new javax.swing.Timer(60*1000,new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent e)
        {
            escreva();
            contador--;
            if(contador == 0)
            {
                
                
                try {
                    new frmLogin().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frmFornecedores.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    });

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmFornecedores().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frmFornecedores.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboFornecedores;
    private com.toedter.calendar.JDateChooser JdcFim;
    private com.toedter.calendar.JDateChooser JdcInicio;
    private javax.swing.JButton btnTotal;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    
    
     SimpleDateFormat formato =
            new SimpleDateFormat("dd/MM/yyyy");
    //Define Formato de Data
    
    
String datainicio, datafim, data;
Date data1, data2;





        public void PreencherCombobox(){
         connCombo.getCon();
         connCombo.executaSql("select Nome_Fantasia from Fornecedor order by Nome_Fantasia");
         ComboFornecedores.removeAllItems();
         try{
         connCombo.rs.first();
         do{
         ComboFornecedores.addItem(connCombo.rs.getString("Nome_Fantasia"));
         
         }while(connCombo.rs.next());
         
         
         }catch(Exception e){
         JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ComboBox"+e);
         }

 
}
}
