/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controlador.ControladorLogin;
import Modelo.clsLogin;
import giovanellis.SqlServer;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class frmLogin extends javax.swing.JFrame {
   private clsLogin usuario;
   
   boolean result;
    Controlador.ControladorLogin DAO;
    
    
    /**
     * Creates new form frmLogin
     */
    public frmLogin() throws Exception {
        SqlServer connCombo = new SqlServer();
        Color Preto = new Color(075,075,075); 
          getContentPane().setBackground(Preto);
          
         this.setIconImage(new ImageIcon(getClass().getResource("/giovanellis/Icone.png")).getImage()); 
        initComponents();
        try{
        DAO = new ControladorLogin();
        } catch(Exception e){
          JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
         connCombo.getCon();
         connCombo.executaSql("select Login_Funcionario from Funcionario ");
         
         try{
         connCombo.rs.first();
         do{
         cmb_Usuario.addItem(connCombo.rs.getString("Login_Funcionario"));
         
         }while(connCombo.rs.next());
         
         
         }catch(Exception e){
         JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ComboBox"+e);
         }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mtxt_senha = new javax.swing.JPasswordField();
        btn_entrar = new javax.swing.JButton();
        btn_entrar1 = new javax.swing.JButton();
        cmb_Usuario = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giovanelli's Pizzaria");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giovanellis/Login2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 260));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha");

        btn_entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giovanellis/enter3.png"))); // NOI18N
        btn_entrar.setText("Entrar");
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });

        btn_entrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giovanellis/delete21.png"))); // NOI18N
        btn_entrar1.setText("Cancelar");
        btn_entrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrar1ActionPerformed(evt);
            }
        });

        cmb_Usuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o usuário..." }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_entrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(btn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_Usuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mtxt_senha))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mtxt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_entrar)
                    .addComponent(btn_entrar1))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 250, 130));

        jMenu1.setText("Alterar Senha");
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(616, 315));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
        if(validarCampos()){
         if(usuarioExiste()){
            JOptionPane.showMessageDialog(this, "Usuário autenticado com sucesso!");
            
            limparLogin();
            
            result = true;
             try {
                 dispose();
                 new frmHome().setVisible(true);
             } catch (Exception ex) {
                 Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
             }
        } else {
            limparLogin();
            result = false;
            cmb_Usuario.requestFocus();   
        }
         
     }
    }//GEN-LAST:event_btn_entrarActionPerformed

    private void btn_entrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_entrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
  
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmLogin().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entrar;
    private javax.swing.JButton btn_entrar1;
    private javax.swing.JComboBox cmb_Usuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField mtxt_senha;
    // End of variables declaration//GEN-END:variables

    public boolean usuarioExiste(){
      boolean opc = false;
      try{
            if(cmb_Usuario.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(this,"Informe o usuário!", "Campo Obrigatório", 2);
            cmb_Usuario.requestFocus();
            } else{
                    setUsuario(DAO.existe((String) cmb_Usuario.getSelectedItem()));
                    if(getUsuario() == null){
                     JOptionPane.showMessageDialog(this, "Usuário não encontrado!");
                     //cmb_Usuario.setText("");
                     mtxt_senha.setText("");
                     cmb_Usuario.requestFocus();
                    }else{
                           setUsuario(DAO.existe((String) cmb_Usuario.getSelectedItem())); //O pesquisar deve retornar a senha 
                           String senha = getUsuario().getSenha();
                           if(mtxt_senha.getText().equals(senha)){
                               opc = true;
                           } else {
                               JOptionPane.showMessageDialog(this, "Senha Inválida");
                           }
                          
                       }
                   } 
            }catch(Exception erro){
            JOptionPane.showMessageDialog(this, "Erro: " + erro.getMessage());
           }
      return opc;   
   }  

  public boolean validarCampos(){
    if(cmb_Usuario.getSelectedItem().equals("")){
       JOptionPane.showMessageDialog(this, "Informe o usuário!");
       cmb_Usuario.requestFocus();
       return false;
    }
    
    if(mtxt_senha.getText().equals("")){
       JOptionPane.showMessageDialog(this, "Informe a senha!");
       mtxt_senha.requestFocus();
       return false;
    }
    return true;
   }  
    
  public void limparLogin(){
     cmb_Usuario.setSelectedIndex(0);
      mtxt_senha.setText("");
  }
  
  public boolean getResult(){
      return result;
  }
  
  public boolean preencherObjeto(){
        setUsuario(new clsLogin());
        getUsuario().setUsuario((String) cmb_Usuario.getSelectedItem());
        getUsuario().setSenha(mtxt_senha.getText());
      return true;
  }

    /**
     * @return the usuario
     */
    public clsLogin getUsuario() {
        return usuario;
    }

    /**
     * @param usuario the usuario to set
     */
    public void setUsuario(clsLogin usuario) {
        this.usuario = usuario;
    }
  
  
}
