/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.ModeloRelatorio;
import Controlador.ControladorRelatorio;
import java.awt.Color;
import javax.swing.ImageIcon;
import giovanellis.SqlServer;
import java.util.logging.Level;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

import javax.mail.Address;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;
//import javafx.stage.FileChooser;






import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.swing.JFileChooser;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Alex
 */
public class frmRelatorios extends javax.swing.JFrame {

    ModeloRelatorio ModeloRelatorio;
    ControladorRelatorio ControladorRelatorio;
    SqlServer conecta;

    /**
     * Creates new form frmRelatorios
     */
    public frmRelatorios() throws Exception {
        conecta = new SqlServer();
        ModeloRelatorio = new ModeloRelatorio();
        ControladorRelatorio = new ControladorRelatorio();
        Color Fundo = new Color(238, 235, 227);
        getContentPane().setBackground(Fundo);
        setAlwaysOnTop(true);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagens/Icone.png")).getImage());
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblInicio1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFim1 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lblRelPromocao = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblInicio2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblFim2 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lblRelPedidos = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblInicio3 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        lblFim3 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lblRelCompras = new javax.swing.JLabel();
        lblInicio4 = new javax.swing.JLabel();
        lblFim4 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        lblRelFuncionario = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        lblInicio5 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        lblFim5 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        lblRelatorioDespesas = new javax.swing.JLabel();
        RD_Pedidos = new javax.swing.JRadioButton();
        RD_Promocao = new javax.swing.JRadioButton();
        RD_Compras = new javax.swing.JRadioButton();
        RD_Funcionarios = new javax.swing.JRadioButton();
        RD_Despesas = new javax.swing.JRadioButton();
        jButton10 = new javax.swing.JButton();
        BtnPdf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JdcInicio = new com.toedter.calendar.JDateChooser();
        JdcFinal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        LblTotalReceitas = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        lblTotalDespesas = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        lblTotalGeral = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setBackground(new java.awt.Color(88, 55, 66));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(239, 111, 83));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Relatório de Promoções");
        jLabel8.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(88, 55, 66));
        jLabel9.setText("Data Inicial");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(239, 111, 83));
        jLabel10.setText("jLabel3");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(88, 55, 66));
        jLabel11.setText("Data Final");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(239, 111, 83));
        jLabel12.setText("jLabel3");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(88, 55, 66));
        jLabel13.setText("Valor Total:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(239, 111, 83));
        jLabel14.setText("jLabel3");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(239, 111, 83));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BotaoRel.png"))); // NOI18N
        jButton2.setText("Limpar");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setOpaque(false);

        jLabel29.setBackground(new java.awt.Color(88, 55, 66));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(239, 111, 83));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Relatório de Promoções");
        jLabel29.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(88, 55, 66));
        jLabel4.setText("Data Inicial");

        lblInicio1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInicio1.setForeground(new java.awt.Color(239, 111, 83));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(88, 55, 66));
        jLabel6.setText("Data Final");

        lblFim1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFim1.setForeground(new java.awt.Color(239, 111, 83));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(88, 55, 66));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Valor Total");

        lblRelPromocao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRelPromocao.setForeground(new java.awt.Color(239, 111, 83));
        lblRelPromocao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRelPromocao.setText("R$");

        jLabel32.setBackground(new java.awt.Color(88, 55, 66));
        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(239, 111, 83));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Relatório de Pedidos");
        jLabel32.setOpaque(true);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(88, 55, 66));
        jLabel23.setText("Data Inicial");

        lblInicio2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInicio2.setForeground(new java.awt.Color(239, 111, 83));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(88, 55, 66));
        jLabel25.setText("Data Final");

        lblFim2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFim2.setForeground(new java.awt.Color(239, 111, 83));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(88, 55, 66));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Valor Total");

        lblRelPedidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRelPedidos.setForeground(new java.awt.Color(239, 111, 83));
        lblRelPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRelPedidos.setText("R$");

        jLabel33.setBackground(new java.awt.Color(88, 55, 66));
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(239, 111, 83));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Relatório de Compras");
        jLabel33.setOpaque(true);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(88, 55, 66));
        jLabel27.setText("Data Inicial");

        lblInicio3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInicio3.setForeground(new java.awt.Color(239, 111, 83));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(88, 55, 66));
        jLabel42.setText("Data Final");

        lblFim3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFim3.setForeground(new java.awt.Color(239, 111, 83));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(88, 55, 66));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Valor Total");

        lblRelCompras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRelCompras.setForeground(new java.awt.Color(239, 111, 83));
        lblRelCompras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRelCompras.setText("R$");

        lblInicio4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInicio4.setForeground(new java.awt.Color(239, 111, 83));

        lblFim4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFim4.setForeground(new java.awt.Color(239, 111, 83));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(88, 55, 66));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Valor Total");

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(88, 55, 66));
        jLabel49.setText("Data Inicial");

        lblRelFuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRelFuncionario.setForeground(new java.awt.Color(239, 111, 83));
        lblRelFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRelFuncionario.setText("R$");

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(88, 55, 66));
        jLabel56.setText("Data Final");

        jLabel57.setBackground(new java.awt.Color(88, 55, 66));
        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(239, 111, 83));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Relatório de Funcionários");
        jLabel57.setOpaque(true);

        jLabel58.setBackground(new java.awt.Color(88, 55, 66));
        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(239, 111, 83));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("Relatório de Despesas");
        jLabel58.setOpaque(true);

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(88, 55, 66));
        jLabel59.setText("Data Inicial");

        lblInicio5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInicio5.setForeground(new java.awt.Color(239, 111, 83));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(88, 55, 66));
        jLabel61.setText("Data Final");

        lblFim5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFim5.setForeground(new java.awt.Color(239, 111, 83));

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(88, 55, 66));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Valor Total");

        lblRelatorioDespesas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRelatorioDespesas.setForeground(new java.awt.Color(239, 111, 83));
        lblRelatorioDespesas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRelatorioDespesas.setText("R$");

        RD_Pedidos.setBackground(new java.awt.Color(88, 55, 66));
        RD_Pedidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RD_Pedidos.setForeground(new java.awt.Color(239, 111, 83));
        RD_Pedidos.setText("Relatório?");
        RD_Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RD_PedidosActionPerformed(evt);
            }
        });

        RD_Promocao.setBackground(new java.awt.Color(88, 55, 66));
        RD_Promocao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RD_Promocao.setForeground(new java.awt.Color(239, 111, 83));
        RD_Promocao.setText("Relatório?");
        RD_Promocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RD_PromocaoActionPerformed(evt);
            }
        });

        RD_Compras.setBackground(new java.awt.Color(88, 55, 66));
        RD_Compras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RD_Compras.setForeground(new java.awt.Color(239, 111, 83));
        RD_Compras.setText("Relatório?");
        RD_Compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RD_ComprasActionPerformed(evt);
            }
        });

        RD_Funcionarios.setBackground(new java.awt.Color(88, 55, 66));
        RD_Funcionarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RD_Funcionarios.setForeground(new java.awt.Color(239, 111, 83));
        RD_Funcionarios.setText("Relatório?");
        RD_Funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RD_FuncionariosActionPerformed(evt);
            }
        });

        RD_Despesas.setBackground(new java.awt.Color(88, 55, 66));
        RD_Despesas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RD_Despesas.setForeground(new java.awt.Color(239, 111, 83));
        RD_Despesas.setText("Relatório?");
        RD_Despesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RD_DespesasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel59)
                        .addGap(18, 18, 18)
                        .addComponent(lblInicio5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel61)
                        .addGap(18, 18, 18)
                        .addComponent(lblFim5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRelatorioDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RD_Despesas))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblFim1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRelPromocao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RD_Promocao))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(lblInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(lblFim2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRelPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RD_Pedidos))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(lblInicio3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel42)
                        .addGap(18, 18, 18)
                        .addComponent(lblFim3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRelCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RD_Compras))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addGap(18, 18, 18)
                        .addComponent(lblInicio4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel56)
                        .addGap(18, 18, 18)
                        .addComponent(lblFim4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRelFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RD_Funcionarios)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblInicio1)
                    .addComponent(jLabel6)
                    .addComponent(lblFim1)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRelPromocao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RD_Promocao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblInicio2)
                    .addComponent(jLabel25)
                    .addComponent(lblFim2)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRelPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RD_Pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lblInicio3)
                    .addComponent(jLabel42)
                    .addComponent(lblFim3)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRelCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RD_Compras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(lblInicio4)
                    .addComponent(jLabel56)
                    .addComponent(lblFim4)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRelFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RD_Funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(lblInicio5)
                    .addComponent(jLabel61)
                    .addComponent(lblFim5)
                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRelatorioDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RD_Despesas, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(239, 111, 83));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/button.png"))); // NOI18N
        jButton10.setText("Calcular");
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 568, 100, 40));

        BtnPdf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnPdf.setForeground(new java.awt.Color(239, 111, 83));
        BtnPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/button.png"))); // NOI18N
        BtnPdf.setText("Gerar PDF");
        BtnPdf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPdfActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 568, 104, 40));

        jLabel1.setBackground(new java.awt.Color(88, 55, 66));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 111, 83));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Relatórios Gerenciais");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 33));

        JdcInicio.setOpaque(false);
        JdcInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JdcInicioPropertyChange(evt);
            }
        });
        getContentPane().add(JdcInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 68, 120, -1));

        JdcFinal.setOpaque(false);
        JdcFinal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JdcFinalPropertyChange(evt);
            }
        });
        getContentPane().add(JdcFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 68, 120, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(88, 55, 66));
        jLabel2.setText("Data Inicial");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 70, 86, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(88, 55, 66));
        jLabel3.setText("Data Final");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 70, 79, 20));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(88, 55, 66));
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("Total Despesas");
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 642, 158, 34));

        LblTotalReceitas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblTotalReceitas.setForeground(new java.awt.Color(239, 111, 83));
        LblTotalReceitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTotalReceitas.setText("R$");
        getContentPane().add(LblTotalReceitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 682, 158, 27));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(88, 55, 66));
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Total Receitas");
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 642, 158, 34));

        lblTotalDespesas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalDespesas.setForeground(new java.awt.Color(239, 111, 83));
        lblTotalDespesas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalDespesas.setText("R$");
        getContentPane().add(lblTotalDespesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 682, 158, 27));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(88, 55, 66));
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("Total Geral");
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 642, 159, 34));

        lblTotalGeral.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalGeral.setForeground(new java.awt.Color(239, 111, 83));
        lblTotalGeral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalGeral.setText("R$");
        getContentPane().add(lblTotalGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 682, 158, 27));

        setSize(new java.awt.Dimension(737, 766));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPdfActionPerformed
       this.setAlwaysOnTop(false);
        
        DefaultPieDataset dpd = new DefaultPieDataset();
        dpd.setValue("Promoções", GPromocoes); 
        dpd.setValue("Pedidos", GPedidos); 
        dpd.setValue("Compras", GCompras); 
        dpd.setValue("Funcionários", GFuncionarios); 
        dpd.setValue("Despesas", GDespesas); 

        JFreeChart grafico = ChartFactory.createPieChart("Resumo por setor",dpd,true, true, false);

        ChartPanel chartPanel = new ChartPanel(grafico);

        try { 
            ChartUtilities.saveChartAsJPEG(new java.io.File("../Giovanellis/Relatorios/PizzaSetor.jpg"), grafico, 700, 600);
        } catch (IOException ex) {
            Logger.getLogger(frmRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
         DefaultPieDataset dpd1 = new DefaultPieDataset();
        dpd1.setValue("Total Despesas", GTotalDespesas); 
        dpd1.setValue("Total Receitas", GTotalReceitas); 
        dpd1.setValue("Total Geral", GTotalGeral); 
        

        JFreeChart grafico1 = ChartFactory.createPieChart("Resumo Geral",dpd1,true, true, false);

        ChartPanel chartPanel1 = new ChartPanel(grafico1);

              
        try { 
            ChartUtilities.saveChartAsJPEG(new java.io.File("../Giovanellis/Relatorios/PizzaTotal.jpg"), grafico1, 700, 600);
        } catch (IOException ex) {
            Logger.getLogger(frmRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        if (BinarioCompras !=0 || BinarioDespesa !=0 || BinarioFuncionario !=0 || BinarioPedidos !=0 || BinarioPromocao!=0)

      {
          int Binario = 0;
          destinatario = null;
          caminho = null;
        
     
          
File pdf = null;
JFileChooser chooser = null;
//int res = chooser.showSaveDialog(home);
try {
  pdf = File.createTempFile("NomedoArquivoSemExtensão",".pdf");            
} catch (IOException e1) {            
  e1.printStackTrace();
}

//Geração do arquivo

chooser = new JFileChooser();
chooser.setCurrentDirectory(pdf);
chooser.setSelectedFile(pdf);
javax.swing.filechooser.FileFilter filter = new javax.swing.filechooser.FileFilter() {  
  
    public boolean accept(File f) {  
        return f.isDirectory()  
                || f.getName().toLowerCase().endsWith(  
                ".pdf");  
    }  
  
    public String getDescription() {  
        return "(*.pdf)";  
        // return "(*.xls)";  
    }  
};  
chooser.addChoosableFileFilter(filter);  
chooser.setAcceptAllFileFilterUsed(false);
chooser.setMultiSelectionEnabled(false);

caminho = "";

int retorno = chooser.showSaveDialog(null);
if (retorno==JFileChooser.APPROVE_OPTION){
  caminho = chooser.getSelectedFile().getAbsolutePath();
}

if(!caminho.equals("")){
  boolean ok = pdf.renameTo(new File(caminho));
  if(ok) {
    
    gerapdf(datainicio, datafim, lblRelPromocao.getText(), lblRelCompras.getText(),
                        lblRelPedidos.getText(), lblRelFuncionario.getText(), lblRelatorioDespesas.getText(),
                        LblTotalReceitas.getText(), lblTotalDespesas.getText(), lblTotalGeral.getText());
    
    
  }
  else
  {
   JOptionPane.showMessageDialog(this, "Erro ao salvar documento"); 
   Binario = 1;  
   this.setAlwaysOnTop(true);
  }
}else{
  //throw new FileNaoSelecionadoException();
}

} else 
      {
      JOptionPane.showMessageDialog(this, "Escolher no mínimo um valor para o relatório");
      }

if (!caminho.equals("")) {
    this.setAlwaysOnTop(false);
            int opcao = JOptionPane.showConfirmDialog(null, "Enviar Relatório por Email?", "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (opcao == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(this, "Envio de email cancelado.");
                this.setAlwaysOnTop(true);
            } else if (opcao == JOptionPane.YES_OPTION) {
                this.setAlwaysOnTop(false);
                for (int e = 0; e <= 3; e++) {
                    destinatario = JOptionPane.showInputDialog(this, "Nome do Destinatário:", "Destinatário", JOptionPane.PLAIN_MESSAGE);
                    
                    if (destinatario.contains("@") && destinatario.contains(".")){
                        
                         if (destinatario == null || destinatario.equals("")) {
                        JOptionPane.showMessageDialog(this, "Você não inseriu um e-mail válido.");
                        if (e == 2) {
                            JOptionPane.showMessageDialog(this, "Email não enviado.");
                            break;

                        }
                    } else {
                        try {
                            EnviarEmail();
                            JOptionPane.showMessageDialog(this, "Email Enviado com Sucesso");
                            BtnPdf.setEnabled(false);
                            this.setAlwaysOnTop(true);
                            break;
                            

                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(this, "O Email não foi enviado.\n Motivo: " + ex);
                            break;
                        }

                    }
                    
                    }else
                    {
                    JOptionPane.showMessageDialog(this, "Destinatário Inválido");
                    }
                   
                }
            }}
 

    }//GEN-LAST:event_BtnPdfActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        if (RD_Compras.isSelected()|| RD_Despesas.isSelected() || RD_Funcionarios.isSelected() || RD_Pedidos.isSelected() || RD_Promocao.isSelected())

      {
          
     
      
        
        try {
            if (ValidaDatas()){
            if (preencheObjeto()) {
                ControladorRelatorio.Incluir(ModeloRelatorio);
                double TotalPromocoes = ControladorRelatorio.getRs().getDouble("Promocoes");
                double TotalPedidos = ControladorRelatorio.getRs().getDouble("Pedidos");
                double TotalCompras = ControladorRelatorio.getRs().getDouble("Compras");
                double TotalFuncionario = ControladorRelatorio.getRs().getDouble("Funcionario");
                double TotalDespesa = ControladorRelatorio.getRs().getDouble("Despesa");

                double Prejuizo = ControladorRelatorio.getRs().getDouble("Prejuizo");
                 double Receita = ControladorRelatorio.getRs().getDouble("Receita");
                 double Geral = ControladorRelatorio.getRs().getDouble("TotalGeral");
                 
                 GCompras = TotalCompras;
                 GDespesas = TotalDespesa;
                 GFuncionarios = TotalFuncionario;
                 GPedidos = TotalPedidos;
                 GPromocoes = TotalPromocoes;
                 
                 GTotalDespesas = Prejuizo;
                 GTotalReceitas = Receita;
                 GTotalGeral = Geral;

                lblRelPromocao.setText(z.format(TotalPromocoes));
                lblRelPedidos.setText(z.format(TotalPedidos));
                lblRelCompras.setText(z.format(TotalCompras));
                lblRelFuncionario.setText(z.format(TotalFuncionario));
                lblRelatorioDespesas.setText(z.format(TotalDespesa));

                lblTotalDespesas.setText(z.format(Prejuizo));
                LblTotalReceitas.setText(z.format(Receita));
                lblTotalGeral.setText(z.format(Geral));
                BtnPdf.setEnabled(true);
            }   
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: "+ex);
        }
}
else
{
 BtnPdf.setEnabled(false);
 lblTotalDespesas.setText("R$ 0,00");
 LblTotalReceitas.setText("R$ 0,00");
 lblTotalGeral.setText("R$ 0,00");
}
    }//GEN-LAST:event_jButton10ActionPerformed

    private void JdcInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JdcInicioPropertyChange
        try {
            data1 = JdcInicio.getDate();
            datainicio = fmt.format(datas(JdcInicio.getDate()));
            dataProcInicio = fmbd.format(JdcInicio.getDate());
            System.out.println(dataProcInicio);
            setarDatas();
            // data receba um formato e formate o método data e guarde na varíável e guarde na caixa de combinação

        } catch (Exception e) {
        }
    }//GEN-LAST:event_JdcInicioPropertyChange

    private void JdcFinalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JdcFinalPropertyChange
        try {
            data2 = JdcFinal.getDate();
            datafim = fmt.format(data(JdcFinal.getDate()));
            dataProcFim = fmbd.format(JdcFinal.getDate());
            System.out.println(dataProcFim);
            SetarDatasFinais();
            // data receba um formato e formate o método data e guarde na varíável e guarde na caixa de combinação

        } catch (Exception e) {
        }            // TODO add your handling code here:

    }//GEN-LAST:event_JdcFinalPropertyChange

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
        timer.stop();
        frmHome.contador = 10;
         frmHome.binario=0;       
   
    }//GEN-LAST:event_formWindowClosing

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        frmHome.contador = 10;
        contador = 10;
    }//GEN-LAST:event_formMouseMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        timer.start();
        Radio();
        BtnPdf.setEnabled(false);
       
    }//GEN-LAST:event_formWindowOpened

    private void RD_PromocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RD_PromocaoActionPerformed
        if (RD_Promocao.isSelected()) {
            BinarioPromocao = 1;
        } else {
            BinarioPromocao = 0;
            lblRelPromocao.setText("R$ 0,00");

        }
    }//GEN-LAST:event_RD_PromocaoActionPerformed

    private void RD_PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RD_PedidosActionPerformed
        if (RD_Pedidos.isSelected()) {
            BinarioPedidos = 1;
        } else {
            BinarioPedidos = 0;
            lblRelPedidos.setText("R$ 0,00");

        }
    }//GEN-LAST:event_RD_PedidosActionPerformed

    private void RD_ComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RD_ComprasActionPerformed
        if (RD_Compras.isSelected()) {
            BinarioCompras = 1;
        } else {
            BinarioCompras = 0;
            lblRelCompras.setText("R$ 0,00");

        }
    }//GEN-LAST:event_RD_ComprasActionPerformed

    private void RD_FuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RD_FuncionariosActionPerformed
        if (RD_Funcionarios.isSelected()) {
            BinarioFuncionario = 1;
        } else {
            BinarioFuncionario = 0;
            lblRelFuncionario.setText("R$ 0,00");

        }
    }//GEN-LAST:event_RD_FuncionariosActionPerformed

    private void RD_DespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RD_DespesasActionPerformed
        if (RD_Despesas.isSelected()) {
            BinarioDespesa = 1;
        } else {
            BinarioDespesa = 0;
            lblRelatorioDespesas.setText("R$ 0,00");

        }
    }//GEN-LAST:event_RD_DespesasActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    
    }//GEN-LAST:event_formWindowClosed
    int contador = 10;

    public void escreva() {
        System.out.println(contador);

    }
    private javax.swing.Timer timer = new javax.swing.Timer(60 * 1000, new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent e) {
            escreva();
            contador--;
            if (contador == 0) {
                timer.stop();
                dispose();
            }
        }
    });

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmRelatorios().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frmRelatorios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPdf;
    private com.toedter.calendar.JDateChooser JdcFinal;
    private com.toedter.calendar.JDateChooser JdcInicio;
    private javax.swing.JLabel LblTotalReceitas;
    private javax.swing.JRadioButton RD_Compras;
    private javax.swing.JRadioButton RD_Despesas;
    private javax.swing.JRadioButton RD_Funcionarios;
    private javax.swing.JRadioButton RD_Pedidos;
    private javax.swing.JRadioButton RD_Promocao;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblFim1;
    private javax.swing.JLabel lblFim2;
    private javax.swing.JLabel lblFim3;
    private javax.swing.JLabel lblFim4;
    private javax.swing.JLabel lblFim5;
    private javax.swing.JLabel lblInicio1;
    private javax.swing.JLabel lblInicio2;
    private javax.swing.JLabel lblInicio3;
    private javax.swing.JLabel lblInicio4;
    private javax.swing.JLabel lblInicio5;
    private javax.swing.JLabel lblRelCompras;
    private javax.swing.JLabel lblRelFuncionario;
    private javax.swing.JLabel lblRelPedidos;
    private javax.swing.JLabel lblRelPromocao;
    private javax.swing.JLabel lblRelatorioDespesas;
    private javax.swing.JLabel lblTotalDespesas;
    private javax.swing.JLabel lblTotalGeral;
    // End of variables declaration//GEN-END:variables
NumberFormat z = NumberFormat.getCurrencyInstance();
    SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat fmbd = new SimpleDateFormat("yyyy-MM-dd");
    DecimalFormat df = new DecimalFormat("#,##0.00");
    Date data1, data2;
    String NomeRelatorio, destinatario;
    String datainicio, datafim, data, dataProcInicio, dataProcFim;
    double Promocao;
    int BinarioFuncionario = 1, BinarioDespesa = 1, BinarioCompras = 1, BinarioPedidos = 1, BinarioPromocao = 1;
    String caminho;
    int Binario;
    double GPromocoes, GFuncionarios, GDespesas, GCompras, GPedidos, GTotalReceitas, GTotalDespesas, GTotalGeral;
    
 

    public boolean ValidaDatas() {
        try {

            if ((data1.getDate() - data2.getDate()) > 0) {
                JOptionPane.showMessageDialog(this, "Data inicial maior que a data final, ou data final menor que a inicial");
                return false;
            }

        } catch (Exception e) {
        }

        if (JdcInicio.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Informe a data Inicial");

            return false;
        }
        if (JdcFinal.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Informe a data Final");

            return false;
        }

        return true;

    }

    public Date datas(Date i) {
        // Método com retorno. Retorna data
        datainicio = fmt.format(i);
        DateFormat df = DateFormat.getDateInstance(DateFormat.LONG, new Locale("pt", "BR"));

        return i;

    }

    public Date data(Date f) {
        // Método com retorno. Retorna data
        datafim = fmt.format(f);
        DateFormat df = DateFormat.getDateInstance(DateFormat.LONG, new Locale("pt", "BR"));

        return f;

    }

    public void setarDatas() {
        lblInicio1.setText(datainicio);
        lblInicio2.setText(datainicio);
        lblInicio3.setText(datainicio);
        lblInicio4.setText(datainicio);
        lblInicio5.setText(datainicio);
    }

    public void SetarDatasFinais() {

        lblFim1.setText(datafim);
        lblFim2.setText(datafim);
        lblFim3.setText(datafim);
        lblFim4.setText(datafim);
        lblFim5.setText(datafim);

    }
    
    
    
    
    public void gerapdf(String dataInicial, String dataFinal, String TotalPromoCoes, String TotalCompras, String TotalPedidos,
            String TotalFuncionarios, String TotalDespesas, String Receita,String Prejuizo, String Geral ) {

        
      
        
        // cria o documento vazio 
        Document DocumentPdf = new Document();

        try {

            // Criar uma nova Cor
            Color Laranja = new Color(242, 184, 171);

            //Criar um estilo de fonte para o Título
            Font h1 = new Font(Font.FontFamily.COURIER, 36, Font.BOLD);
            Font h2 = new Font(Font.FontFamily.COURIER, 25, Font.BOLD);
            Font h3 = new Font(Font.FontFamily.COURIER, 18, Font.BOLD);

            // Cria uma instancia e dá o nome para o pdf    
           // PdfWriter.getInstance(DocumentPdf, new FileOutputStream("../Giovanellis/Relatorios/" + NomeRelatorio + ".pdf"));
            PdfWriter.getInstance(DocumentPdf, new FileOutputStream(caminho));
            // abrir o documento
            DocumentPdf.open();

            // Setar o tamanho da página
            DocumentPdf.setPageSize(PageSize.A4);

            //Adicionar Primeiro parágrago do Título
            Paragraph Titulo = new Paragraph("Giovanelli's Relatório's", h1);
            Titulo.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(Titulo);

            
            
            // Mencionando a instância da Imagem
            Image Cabecalho = Image.getInstance("../Giovanellis/Marca.png");
            
            
            //Setar o tamanho em pixels da imagem
            Cabecalho.scaleToFit(400, 200);

            //Centraliza a Imagem
            Cabecalho.setAlignment(Element.ALIGN_CENTER);

            // Adicionar a imagem ao PDF
            DocumentPdf.add(Cabecalho);

            Paragraph datas = new Paragraph("Data Inicial: " + dataInicial + "  Data Final: " + dataFinal + "\n" + "\n", h3);
            datas.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(datas);

            Paragraph Setor = new Paragraph("Resumo por Setor:" + "\n" + "\n", h2);
            Setor.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(Setor);

            if (BinarioPromocao == 1) {
                Paragraph Promocao = new Paragraph("Descritivos de Promoções: " + TotalPromoCoes + "\n", h3);
                Promocao.setAlignment(Element.ALIGN_CENTER);
                DocumentPdf.add(Promocao);

            }

            if (BinarioPedidos == 1) {
                Paragraph Pedidos = new Paragraph("Descritivos de Pedidos: " + TotalPedidos + "\n", h3);
                Pedidos.setAlignment(Element.ALIGN_CENTER);
                DocumentPdf.add(Pedidos);
            }

            if (BinarioCompras == 1) {

                Paragraph Compras = new Paragraph("Descritivos de Compras: " + TotalCompras + "\n", h3);
                Compras.setAlignment(Element.ALIGN_CENTER);
                DocumentPdf.add(Compras);
            }

            if (BinarioFuncionario == 1) {
                Paragraph Funcioarios = new Paragraph("Descritivos de Funcionarios: " + TotalFuncionarios + "\n", h3);
                Funcioarios.setAlignment(Element.ALIGN_CENTER);
                DocumentPdf.add(Funcioarios);
            }

            if (BinarioDespesa == 1) {
                Paragraph Despesa = new Paragraph("Descritivos de Despesas: " + TotalDespesas + "\n", h3);
                Despesa.setAlignment(Element.ALIGN_CENTER);
                DocumentPdf.add(Despesa);
            }
            
            
            Paragraph Total = new Paragraph("\n Resumo Geral:", h2);
            Total.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(Total);

            Paragraph DescritivoDespesa = new Paragraph("\n Total de Despesas: " + Prejuizo + "\n", h3);
            DescritivoDespesa.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(DescritivoDespesa);

            Paragraph DescritivoReceitas = new Paragraph("Total de Receitas: " + Receita + "\n", h3);
            DescritivoReceitas.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(DescritivoReceitas);
           
            Paragraph TotalGeralR = new Paragraph("Total Geral: " + Geral + "\n", h3);
            TotalGeralR.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(TotalGeralR);

            
            Paragraph Espaço = new Paragraph("\n\n");
            
            //Cria uma Nova Página
             DocumentPdf.newPage();
             
             DocumentPdf.add(Titulo);
            
             DocumentPdf.add(Espaço);
             
            Image Grafico1 = Image.getInstance("../Giovanellis/Relatorios/PizzaSetor.jpg");
           
            Grafico1.scaleToFit(500, 300);

            Grafico1.setAlignment(Element.ALIGN_CENTER);
                    
            Image Grafico2 = Image.getInstance("../Giovanellis/Relatorios/PizzaTotal.jpg");
            
            Grafico2.scaleToFit(500, 300);

            Grafico2.setAlignment(Element.ALIGN_CENTER);
             
             

            
            DocumentPdf.add(Grafico1);
            
            DocumentPdf.add(Espaço);
            
            DocumentPdf.add(Grafico2);
            
            
             
            JOptionPane.showMessageDialog(this, "Arquivo Gerado com Sucesso \nCaminho:" + caminho);
            this.setAlwaysOnTop(true);

        } catch (DocumentException e) {
            e.printStackTrace();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } finally {
            DocumentPdf.close();
        }

    }

    public void EnviarEmail() {
//         while (destinatario == null || destinatario.equals("")) {

        Properties props = new Properties();
        /**
         * Parâmetros de conexão com servidor Gmail
         */
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", "465");

        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication("acs@hotelclubeazuldomar.com.br", "hotel3424");
                    }
                });

        /**
         * Ativa Debug para sessão
         */
        session.setDebug(true);

        try {

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("seuemail@gmail.com")); //Remetente

            Address[] toUser = InternetAddress //Destinatário(s)
                    .parse(destinatario);

            message.setRecipients(Message.RecipientType.TO, toUser);
            message.setSubject("Giovaneli's Relatório's enviado pelo Java");//Assunto
            message.setText("Anexo do Giovaneli's Relatório's do período solicitado");

            FileDataSource source = new FileDataSource(
                    caminho);
            message.setDataHandler(new DataHandler(source));
            message.setFileName(source.getName());

            /**
             * Método para enviar a mensagem criada
             */
            Transport.send(message);

            // JOptionPane.showMessageDialog(null, "E-mail Enviado com Sucesso");
        } catch (MessagingException e) {
            throw new RuntimeException(e);

        }

    }

    public void Binarios() {
        BinarioCompras = 1;
        BinarioDespesa = 1;
        BinarioFuncionario = 1;
        BinarioPedidos = 1;
        BinarioPromocao = 1;

    }

    public boolean preencheObjeto() {

        ModeloRelatorio.setDataInicial(dataProcInicio);
        ModeloRelatorio.setDataFinal(dataProcFim);
        ModeloRelatorio.setBinarioCompras(BinarioCompras);
        ModeloRelatorio.setBinarioDespesa(BinarioDespesa);
        ModeloRelatorio.setBinarioFuncionario(BinarioFuncionario);
        ModeloRelatorio.setBinarioPedidos(BinarioPedidos);
        ModeloRelatorio.setBinarioPromocao(BinarioPromocao);

        return true;
    }

    public void Radio() {
        RD_Compras.setSelected(true);
        RD_Despesas.setSelected(true);
        RD_Funcionarios.setSelected(true);
        RD_Pedidos.setSelected(true);
        RD_Promocao.setSelected(true);

    }
  
    
}


