/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;
import Modelo.ModeloRelatorio;
import Controlador.ControladorRelatorio;
import java.awt.Color;
import javax.swing.ImageIcon;
import giovanellis.SqlServer;
import java.util.logging.Level;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Calendar;

import javax.mail.Address;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;

/**
 *
 * @author Alex
 */
public class frmRelatorios extends javax.swing.JFrame {
    ModeloRelatorio ModeloRelatorio;
    ControladorRelatorio ControladorRelatorio;
    SqlServer conecta;

    /**
     * Creates new form frmRelatorios
     */
    public frmRelatorios() throws Exception {
        conecta = new SqlServer();
        ModeloRelatorio = new ModeloRelatorio();
        ControladorRelatorio = new ControladorRelatorio();
        Color Fundo = new Color(238, 235, 227);
        getContentPane().setBackground(Fundo);
        //setAlwaysOnTop(true);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagens/Icone.png")).getImage());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblInicio1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFim1 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        JlblTotalPromocao = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblInicio2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblFim2 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        JlblTotalPedidos = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblInicio3 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        lblFim3 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        JlblTotalCompras = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        lblInicio4 = new javax.swing.JLabel();
        lblFim4 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        JlblTotalFuncionarios = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        lblInicio5 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        lblFim5 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        JlblTotalDespesas = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        BtnPdf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JdcInicio = new com.toedter.calendar.JDateChooser();
        JdcFinal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        JlblTotalReceitas = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        JlblTotalGeralDespesas = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        JlblTotalGeral = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setBackground(new java.awt.Color(88, 55, 66));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(239, 111, 83));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Relatório de Promoções");
        jLabel8.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(88, 55, 66));
        jLabel9.setText("Data Inicial");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(239, 111, 83));
        jLabel10.setText("jLabel3");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(88, 55, 66));
        jLabel11.setText("Data Final");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(239, 111, 83));
        jLabel12.setText("jLabel3");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(88, 55, 66));
        jLabel13.setText("Valor Total:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(239, 111, 83));
        jLabel14.setText("jLabel3");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(239, 111, 83));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BotaoRel.png"))); // NOI18N
        jButton2.setText("Limpar");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setOpaque(false);

        jLabel29.setBackground(new java.awt.Color(88, 55, 66));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(239, 111, 83));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Relatório de Promoções");
        jLabel29.setOpaque(true);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(239, 111, 83));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BotaoRel.png"))); // NOI18N
        jButton5.setText("Limpar");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(88, 55, 66));
        jLabel4.setText("Data Inicial");

        lblInicio1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInicio1.setForeground(new java.awt.Color(239, 111, 83));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(88, 55, 66));
        jLabel6.setText("Data Final");

        lblFim1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFim1.setForeground(new java.awt.Color(239, 111, 83));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(88, 55, 66));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Valor Total");

        JlblTotalPromocao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JlblTotalPromocao.setForeground(new java.awt.Color(239, 111, 83));
        JlblTotalPromocao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JlblTotalPromocao.setText("R$");

        jLabel32.setBackground(new java.awt.Color(88, 55, 66));
        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(239, 111, 83));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Relatório de Pedidos");
        jLabel32.setOpaque(true);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(88, 55, 66));
        jLabel23.setText("Data Inicial");

        lblInicio2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInicio2.setForeground(new java.awt.Color(239, 111, 83));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(88, 55, 66));
        jLabel25.setText("Data Final");

        lblFim2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFim2.setForeground(new java.awt.Color(239, 111, 83));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(88, 55, 66));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Valor Total");

        JlblTotalPedidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JlblTotalPedidos.setForeground(new java.awt.Color(239, 111, 83));
        JlblTotalPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JlblTotalPedidos.setText("R$");

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(239, 111, 83));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BotaoRel.png"))); // NOI18N
        jButton8.setText("Limpar");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel33.setBackground(new java.awt.Color(88, 55, 66));
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(239, 111, 83));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Relatório de Compras");
        jLabel33.setOpaque(true);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(88, 55, 66));
        jLabel27.setText("Data Inicial");

        lblInicio3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInicio3.setForeground(new java.awt.Color(239, 111, 83));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(88, 55, 66));
        jLabel42.setText("Data Final");

        lblFim3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFim3.setForeground(new java.awt.Color(239, 111, 83));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(88, 55, 66));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Valor Total");

        JlblTotalCompras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JlblTotalCompras.setForeground(new java.awt.Color(239, 111, 83));
        JlblTotalCompras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JlblTotalCompras.setText("R$");

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(239, 111, 83));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BotaoRel.png"))); // NOI18N
        jButton9.setText("Limpar");
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(239, 111, 83));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BotaoRel.png"))); // NOI18N
        jButton12.setText("Limpar");
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblInicio4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInicio4.setForeground(new java.awt.Color(239, 111, 83));

        lblFim4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFim4.setForeground(new java.awt.Color(239, 111, 83));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(88, 55, 66));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Valor Total");

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(88, 55, 66));
        jLabel49.setText("Data Inicial");

        JlblTotalFuncionarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JlblTotalFuncionarios.setForeground(new java.awt.Color(239, 111, 83));
        JlblTotalFuncionarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JlblTotalFuncionarios.setText("R$");

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(88, 55, 66));
        jLabel56.setText("Data Final");

        jLabel57.setBackground(new java.awt.Color(88, 55, 66));
        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(239, 111, 83));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Relatório de Funcionários");
        jLabel57.setOpaque(true);

        jLabel58.setBackground(new java.awt.Color(88, 55, 66));
        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(239, 111, 83));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("Relatório de Despesas");
        jLabel58.setOpaque(true);

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(88, 55, 66));
        jLabel59.setText("Data Inicial");

        lblInicio5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInicio5.setForeground(new java.awt.Color(239, 111, 83));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(88, 55, 66));
        jLabel61.setText("Data Final");

        lblFim5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFim5.setForeground(new java.awt.Color(239, 111, 83));

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(88, 55, 66));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Valor Total");

        JlblTotalDespesas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JlblTotalDespesas.setForeground(new java.awt.Color(239, 111, 83));
        JlblTotalDespesas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JlblTotalDespesas.setText("R$");

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(239, 111, 83));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BotaoRel.png"))); // NOI18N
        jButton13.setText("Limpar");
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblFim1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JlblTotalPromocao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(lblInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(lblFim2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JlblTotalPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(lblInicio3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel42)
                        .addGap(18, 18, 18)
                        .addComponent(lblFim3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JlblTotalCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addGap(18, 18, 18)
                        .addComponent(lblInicio4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel56)
                        .addGap(18, 18, 18)
                        .addComponent(lblFim4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JlblTotalFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel59)
                        .addGap(18, 18, 18)
                        .addComponent(lblInicio5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel61)
                        .addGap(18, 18, 18)
                        .addComponent(lblFim5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JlblTotalDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblInicio1)
                    .addComponent(jLabel6)
                    .addComponent(lblFim1)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlblTotalPromocao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblInicio2)
                    .addComponent(jLabel25)
                    .addComponent(lblFim2)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlblTotalPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lblInicio3)
                    .addComponent(jLabel42)
                    .addComponent(lblFim3)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlblTotalCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(lblInicio4)
                    .addComponent(jLabel56)
                    .addComponent(lblFim4)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlblTotalFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(lblInicio5)
                    .addComponent(jLabel61)
                    .addComponent(lblFim5)
                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlblTotalDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(239, 111, 83));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/button.png"))); // NOI18N
        jButton10.setText("Calcular");
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        BtnPdf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnPdf.setForeground(new java.awt.Color(239, 111, 83));
        BtnPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/button.png"))); // NOI18N
        BtnPdf.setText("Gerar PDF");
        BtnPdf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPdfActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(88, 55, 66));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 111, 83));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Relatórios Gerenciais");
        jLabel1.setOpaque(true);

        JdcInicio.setOpaque(false);
        JdcInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JdcInicioPropertyChange(evt);
            }
        });

        JdcFinal.setOpaque(false);
        JdcFinal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JdcFinalPropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(88, 55, 66));
        jLabel2.setText("Data Inicial");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(88, 55, 66));
        jLabel3.setText("Data Final");

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(88, 55, 66));
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("Total Despesas");

        JlblTotalReceitas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JlblTotalReceitas.setForeground(new java.awt.Color(239, 111, 83));
        JlblTotalReceitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlblTotalReceitas.setText("R$");

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(88, 55, 66));
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Total Receitas");

        JlblTotalGeralDespesas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JlblTotalGeralDespesas.setForeground(new java.awt.Color(239, 111, 83));
        JlblTotalGeralDespesas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlblTotalGeralDespesas.setText("R$");

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(88, 55, 66));
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("Total Geral");

        JlblTotalGeral.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JlblTotalGeral.setForeground(new java.awt.Color(239, 111, 83));
        JlblTotalGeral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlblTotalGeral.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(JdcInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(JdcFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(BtnPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlblTotalReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(JlblTotalGeralDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(JlblTotalGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JdcInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JdcFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlblTotalReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlblTotalGeralDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlblTotalGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(738, 766));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPdfActionPerformed
        NomeRelatorio = null;
        destinatario = null;
        int Binario = 0;

        for (int i = 0; i <= 3; i++) {

            NomeRelatorio = JOptionPane.showInputDialog(this, "Nome do Relatório:", "Relatório", JOptionPane.PLAIN_MESSAGE);
            if (NomeRelatorio == null || NomeRelatorio.equals("")) {
                JOptionPane.showMessageDialog(this, "Você não inseriu um nome.");
                if (i == 2) {
                    Binario = 1;
                    JOptionPane.showMessageDialog(this, "Relatório Cancelado.");
                    break;

                }
            } else {
                Binario = 0;
                gerapdf(datainicio, datafim, JlblTotalPromocao.getText(), JlblTotalCompras.getText(),
                        JlblTotalPedidos.getText(), JlblTotalFuncionarios.getText(), JlblTotalDespesas.getText(),
                        JlblTotalReceitas.getText(), JlblTotalGeralDespesas.getText(), JlblTotalGeral.getText());

                break;

            }
        }

        if (Binario == 0) {
            int opcao = JOptionPane.showConfirmDialog(null, "Enviar Relatório por Email?", "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (opcao == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(this, "Envio de email cancelado.");

            } else if (opcao == JOptionPane.YES_OPTION) {

                for (int e = 0; e <= 3; e++) {
                    destinatario = JOptionPane.showInputDialog(this, "Nome do Destinatário:", "Destinatário", JOptionPane.PLAIN_MESSAGE);

                    if (destinatario == null || destinatario.equals("")) {
                        JOptionPane.showMessageDialog(this, "Você não inseriu um nome.");
                        if (e == 2) {
                            JOptionPane.showMessageDialog(this, "Email não enviado.");
                            break;

                        }
                    } else {
                        try {
                            EnviarEmail();
                            JOptionPane.showMessageDialog(this, "Email Enviado com Sucesso");
                            break;

                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(this, "O Email não foi enviado.\n Motivo: " + ex);
                            break;
                        }

                    }
                }
            }
        }


    }//GEN-LAST:event_BtnPdfActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            ControladorRelatorio.Incluir(ModeloRelatorio);
        } catch (Exception ex) {
            Logger.getLogger(frmRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void JdcInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JdcInicioPropertyChange
        try {
            data1 = JdcInicio.getDate();
            datainicio = fmt.format(datas(JdcInicio.getDate()));
            dataProcInicio = fmbd.format(JdcInicio.getDate());
            System.out.println(dataProcInicio);
            setarDatas();
            // data receba um formato e formate o método data e guarde na varíável e guarde na caixa de combinação

        } catch (Exception e) {
        }
    }//GEN-LAST:event_JdcInicioPropertyChange

    private void JdcFinalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JdcFinalPropertyChange
        try {
            data2 = JdcFinal.getDate();
            datafim = fmt.format(data(JdcFinal.getDate()));
           dataProcFim = fmbd.format(JdcFinal.getDate());
            System.out.println(dataProcFim);
            SetarDatasFinais();
            // data receba um formato e formate o método data e guarde na varíável e guarde na caixa de combinação

        } catch (Exception e) {
        }            // TODO add your handling code here:

    }//GEN-LAST:event_JdcFinalPropertyChange

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        timer.stop();
        frmHome.contador = 10;
    }//GEN-LAST:event_formWindowClosing

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        frmHome.contador = 10;
        contador = 10;
    }//GEN-LAST:event_formMouseMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        timer.start();
    }//GEN-LAST:event_formWindowOpened
    int contador = 10;

    public void escreva() {
        System.out.println(contador);

    }
    private javax.swing.Timer timer = new javax.swing.Timer(60 * 1000, new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent e) {
            escreva();
            contador--;
            if (contador == 0) {
                timer.stop();
                dispose();
            }
        }
    });

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmRelatorios().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frmRelatorios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPdf;
    private com.toedter.calendar.JDateChooser JdcFinal;
    private com.toedter.calendar.JDateChooser JdcInicio;
    private javax.swing.JLabel JlblTotalCompras;
    private javax.swing.JLabel JlblTotalDespesas;
    private javax.swing.JLabel JlblTotalFuncionarios;
    private javax.swing.JLabel JlblTotalGeral;
    private javax.swing.JLabel JlblTotalGeralDespesas;
    private javax.swing.JLabel JlblTotalPedidos;
    private javax.swing.JLabel JlblTotalPromocao;
    private javax.swing.JLabel JlblTotalReceitas;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblFim1;
    private javax.swing.JLabel lblFim2;
    private javax.swing.JLabel lblFim3;
    private javax.swing.JLabel lblFim4;
    private javax.swing.JLabel lblFim5;
    private javax.swing.JLabel lblInicio1;
    private javax.swing.JLabel lblInicio2;
    private javax.swing.JLabel lblInicio3;
    private javax.swing.JLabel lblInicio4;
    private javax.swing.JLabel lblInicio5;
    // End of variables declaration//GEN-END:variables
NumberFormat z = NumberFormat.getCurrencyInstance();
    SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat fmbd = new SimpleDateFormat("yyyy-MM-dd");
    DecimalFormat df = new DecimalFormat("#,##0.00");
    Date data1, data2;
    String NomeRelatorio, destinatario;
    String datainicio, datafim, data, dataProcInicio, dataProcFim;

    public boolean ValidaDatas() {
        try {

            if ((data1.getDate() - data2.getDate()) > 0) {
                JOptionPane.showMessageDialog(this, "Data inicial maior que a data final, ou data final menor que a inicial");
                return false;
            }

        } catch (Exception e) {
        }

        if (JdcInicio.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Informe a data Inicial");

            return false;
        }
        if (JdcFinal.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Informe a data Final");

            return false;
        }

        return true;

    }

    public Date datas(Date i) {
        // Método com retorno. Retorna data
        datainicio = fmt.format(i);
        DateFormat df = DateFormat.getDateInstance(DateFormat.LONG, new Locale("pt", "BR"));

        return i;

    }

    public Date data(Date f) {
        // Método com retorno. Retorna data
        datafim = fmt.format(f);
        DateFormat df = DateFormat.getDateInstance(DateFormat.LONG, new Locale("pt", "BR"));

        return f;

    }

    public void setarDatas() {
        lblInicio1.setText(datainicio);
        lblInicio2.setText(datainicio);
        lblInicio3.setText(datainicio);
        lblInicio4.setText(datainicio);
        lblInicio5.setText(datainicio);
    }

    public void SetarDatasFinais() {

        lblFim1.setText(datafim);
        lblFim2.setText(datafim);
        lblFim3.setText(datafim);
        lblFim4.setText(datafim);
        lblFim5.setText(datafim);

    }

    public void gerapdf(String dataInicial, String dataFinal, String TotalPromoCoes, String TotalCompras, String TotalPedidos,
            String TotalFuncionarios, String TotalDespesas, String TotalReceitas, String TotalDespesasGeral, String TotalGeral) {

        // cria o documento vazio 
        Document DocumentPdf = new Document();

        try {

            // Criar uma nova Cor
            Color Laranja = new Color(242, 184, 171);

            //Criar um estilo de fonte para o Título
            Font h1 = new Font(Font.FontFamily.COURIER, 36, Font.BOLD);
            Font h2 = new Font(Font.FontFamily.COURIER, 25, Font.BOLD);
            Font h3 = new Font(Font.FontFamily.COURIER, 18, Font.BOLD);
            Font h4 = new Font(Font.FontFamily.COURIER, 14, Font.BOLD);
            // Cria uma instancia e dá o nome para o pdf    
            PdfWriter.getInstance(DocumentPdf, new FileOutputStream("../Giovanellis/Relatorios/" + NomeRelatorio + ".pdf"));
            // abrir o documento
            DocumentPdf.open();

            // Setar o tamanho da página
            DocumentPdf.setPageSize(PageSize.A4);

            //Adicionar Primeiro parágrago do Título
            Paragraph Titulo = new Paragraph("Giovanelli's Relatório's", h1);
            Titulo.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(Titulo);

            // Mencionando a instância da Imagem
            Image Cabecalho = Image.getInstance("../Giovanellis/Marca.png");

            //Setar o tamanho em pixels da imagem
            Cabecalho.scaleToFit(400, 200);

            //Centraliza a Imagem
            Cabecalho.setAlignment(Element.ALIGN_CENTER);

            // Adicionar a imagem ao PDF
            DocumentPdf.add(Cabecalho);

            Paragraph datas = new Paragraph("Data Inicial: " + dataInicial + "             Data Final: " + dataFinal + "\n" + "\n", h4);
            datas.setAlignment(Element.ALIGN_LEFT);
            DocumentPdf.add(datas);

            Paragraph Promocao = new Paragraph("Descritivos de Promoções: " + TotalPromoCoes + "\n", h3);
            Promocao.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(Promocao);

            Paragraph Pedidos = new Paragraph("Descritivos de Pedidos: " + TotalPedidos + "\n", h3);
            Pedidos.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(Pedidos);

            Paragraph Compras = new Paragraph("Descritivos de Compras: " + TotalCompras + "\n", h3);
            Compras.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(Compras);

            Paragraph Funcioarios = new Paragraph("Descritivos de Funcionarios: " + TotalFuncionarios + "\n", h3);
            Funcioarios.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(Funcioarios);

            Paragraph Despesa = new Paragraph("Descritivos de Despesas: " + TotalDespesas + "\n", h3);
            Despesa.setAlignment(Element.ALIGN_CENTER);
            DocumentPdf.add(Despesa);

            //Cria uma Nova Página
            DocumentPdf.newPage();

            DocumentPdf.add(Titulo);

            DocumentPdf.add(Cabecalho);

            DocumentPdf.add(datas);

            JOptionPane.showMessageDialog(this, "Arquivo Gerado com Sucesso \nCaminho: Giovanellis/Relatorios/" + NomeRelatorio + ".pdf");

        } catch (DocumentException e) {
            e.printStackTrace();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } finally {
            DocumentPdf.close();
        }

    }

    public void EnviarEmail() {
//         while (destinatario == null || destinatario.equals("")) {

        Properties props = new Properties();
        /**
         * Parâmetros de conexão com servidor Gmail
         */
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", "465");

        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication("acs@hotelclubeazuldomar.com.br", "hotel3424");
                    }
                });

        /**
         * Ativa Debug para sessão
         */
        session.setDebug(true);

        try {

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("seuemail@gmail.com")); //Remetente

            Address[] toUser = InternetAddress //Destinatário(s)
                    .parse(destinatario);

            message.setRecipients(Message.RecipientType.TO, toUser);
            message.setSubject("Giovaneli's Relatório's enviado pelo Java");//Assunto
            message.setText("Anexo do Giovaneli's Relatório's do período solicitado");

            FileDataSource source = new FileDataSource(
                    "../Giovanellis/Relatorios/" + NomeRelatorio + ".pdf");
            message.setDataHandler(new DataHandler(source));
            message.setFileName(source.getName());

            /**
             * Método para enviar a mensagem criada
             */
            Transport.send(message);

           // JOptionPane.showMessageDialog(null, "E-mail Enviado com Sucesso");
        } catch (MessagingException e) {
            throw new RuntimeException(e);

        }

    }
    
  public boolean preencheObjeto() {
  
        ModeloRelatorio.setDataInicial(dataProcInicio);
        ModeloRelatorio.setDataFinal(dataProcFim);

        return true;
    }

}
