package Visao;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alex
 */
public class frmCalculadora extends javax.swing.JFrame {

    DecimalFormat df;
    int Clique = 1;

    /**
     * Creates new form frmCalculadora
     */
    public frmCalculadora() {
        initComponents();
        df = new DecimalFormat("#,##0.00");
        Color Fundo = new Color(238, 235, 227);
        this.getContentPane().setBackground(Fundo);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagens/Icone.png")).getImage());

        lblResultado.setText("0");

        jButton3.setBackground(new Color(88, 55, 66));
        jButtonSoma.setBackground(new Color(88, 55, 66));
        jButton4.setBackground(new Color(88, 55, 66));
        jButton5.setBackground(new Color(88, 55, 66));
        jButton6.setBackground(new Color(88, 55, 66));
        jButtonSubtracao.setBackground(new Color(88, 55, 66));
        jButton7.setBackground(new Color(88, 55, 66));
        jButton8.setBackground(new Color(88, 55, 66));
        jButton9.setBackground(new Color(88, 55, 66));
        jButtonMultiplicacao.setBackground(new Color(88, 55, 66));
        jButtonZero.setBackground(new Color(88, 55, 66));
        jButtonVirgula.setBackground(new Color(88, 55, 66));
        jButtonIgual.setBackground(new Color(239, 111, 83));
        jButtonGuardar.setBackground(new Color(88, 55, 66));
        jButton1.setBackground(new Color(88, 55, 66));
        jButton2.setBackground(new Color(88, 55, 66));
        setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonZero = new javax.swing.JButton();
        jButtonVirgula = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonSoma = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonSubtracao = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonMultiplicacao = new javax.swing.JButton();
        jButtonBackspace = new javax.swing.JButton();
        jButtonAlterarValor = new javax.swing.JButton();
        jButtonPorcentagem = new javax.swing.JButton();
        jButtonDivisao = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        Display = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();
        lblMontante = new javax.swing.JLabel();
        lblMemoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Giovanelli's Calculator");
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setName("Giovanelli's Calculator"); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonZero.setBackground(new java.awt.Color(88, 55, 66));
        jButtonZero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonZero.setForeground(new java.awt.Color(239, 111, 83));
        jButtonZero.setText("0");
        jButtonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZeroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonZero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 306, 140, 29));

        jButtonVirgula.setBackground(new java.awt.Color(88, 55, 66));
        jButtonVirgula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonVirgula.setForeground(new java.awt.Color(239, 111, 83));
        jButtonVirgula.setText(".");
        jButtonVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVirgulaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVirgula, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 306, 61, 29));

        jButtonIgual.setBackground(new java.awt.Color(239, 111, 83));
        jButtonIgual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonIgual.setForeground(new java.awt.Color(88, 55, 66));
        jButtonIgual.setText("=");
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 306, 61, 29));

        jButton1.setBackground(new java.awt.Color(88, 55, 66));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(239, 111, 83));
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 266, 61, 29));

        jButton2.setBackground(new java.awt.Color(88, 55, 66));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(239, 111, 83));
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 266, 61, 29));

        jButton3.setBackground(new java.awt.Color(88, 55, 66));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(239, 111, 83));
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 266, 61, 29));

        jButtonSoma.setBackground(new java.awt.Color(88, 55, 66));
        jButtonSoma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSoma.setForeground(new java.awt.Color(239, 111, 83));
        jButtonSoma.setText("+");
        jButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 266, 61, 29));

        jButton4.setBackground(new java.awt.Color(88, 55, 66));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(239, 111, 83));
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 226, 61, 29));

        jButton5.setBackground(new java.awt.Color(88, 55, 66));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(239, 111, 83));
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 226, 61, 29));

        jButton6.setBackground(new java.awt.Color(88, 55, 66));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(239, 111, 83));
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 226, 61, 29));

        jButtonSubtracao.setBackground(new java.awt.Color(88, 55, 66));
        jButtonSubtracao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSubtracao.setForeground(new java.awt.Color(239, 111, 83));
        jButtonSubtracao.setText("-");
        jButtonSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtracaoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSubtracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 226, 61, 29));

        jButton7.setBackground(new java.awt.Color(88, 55, 66));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(239, 111, 83));
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 186, 61, 29));

        jButton8.setBackground(new java.awt.Color(88, 55, 66));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(239, 111, 83));
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 186, 61, 29));

        jButton9.setBackground(new java.awt.Color(88, 55, 66));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(239, 111, 83));
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 186, 61, 29));

        jButtonMultiplicacao.setBackground(new java.awt.Color(88, 55, 66));
        jButtonMultiplicacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonMultiplicacao.setForeground(new java.awt.Color(239, 111, 83));
        jButtonMultiplicacao.setText("X");
        jButtonMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacaoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMultiplicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 186, 61, 29));

        jButtonBackspace.setBackground(new java.awt.Color(88, 55, 66));
        jButtonBackspace.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonBackspace.setForeground(new java.awt.Color(239, 111, 83));
        jButtonBackspace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Backspace.png"))); // NOI18N
        jButtonBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackspaceActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBackspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 146, 61, 29));

        jButtonAlterarValor.setBackground(new java.awt.Color(88, 55, 66));
        jButtonAlterarValor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAlterarValor.setForeground(new java.awt.Color(239, 111, 83));
        jButtonAlterarValor.setText("+/-");
        jButtonAlterarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarValorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAlterarValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 146, 61, 29));

        jButtonPorcentagem.setBackground(new java.awt.Color(88, 55, 66));
        jButtonPorcentagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPorcentagem.setForeground(new java.awt.Color(239, 111, 83));
        jButtonPorcentagem.setText("%");
        jButtonPorcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPorcentagemActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPorcentagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 146, 61, 29));

        jButtonDivisao.setBackground(new java.awt.Color(88, 55, 66));
        jButtonDivisao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDivisao.setForeground(new java.awt.Color(239, 111, 83));
        jButtonDivisao.setText("/");
        jButtonDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisaoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDivisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 146, 61, 29));

        jButtonApagar.setBackground(new java.awt.Color(88, 55, 66));
        jButtonApagar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonApagar.setForeground(new java.awt.Color(239, 111, 83));
        jButtonApagar.setText("C");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, 61, 29));

        jButton25.setBackground(new java.awt.Color(88, 55, 66));
        jButton25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton25.setForeground(new java.awt.Color(239, 111, 83));
        jButton25.setText("MC");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 106, 61, 29));

        jButton26.setBackground(new java.awt.Color(88, 55, 66));
        jButton26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton26.setForeground(new java.awt.Color(239, 111, 83));
        jButton26.setText("MR");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 106, 61, 29));

        jButtonGuardar.setBackground(new java.awt.Color(88, 55, 66));
        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(239, 111, 83));
        jButtonGuardar.setText("M+");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 106, 61, 29));

        Display.setBackground(new java.awt.Color(255, 255, 255));
        Display.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Display.setOpaque(false);

        lblResultado.setBackground(new java.awt.Color(238, 235, 227));
        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblResultado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblMontante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMontante.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblMemoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMemoria.setForeground(new java.awt.Color(239, 111, 83));
        lblMemoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout DisplayLayout = new javax.swing.GroupLayout(Display);
        Display.setLayout(DisplayLayout);
        DisplayLayout.setHorizontalGroup(
            DisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayLayout.createSequentialGroup()
                .addComponent(lblMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMontante, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap())
        );
        DisplayLayout.setVerticalGroup(
            DisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisplayLayout.createSequentialGroup()
                .addComponent(lblMontante, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(DisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 298, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(324, 373));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        lblResultado.setText(Memoria);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButtonMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacaoActionPerformed
        if (!lblResultado.getText().equals("0")) {
            valor1 = Double.parseDouble(lblResultado.getText());
            Operacao = "*";
            lblMontante.setText(valor1 + "" + Operacao);
            lblResultado.setText("");
            montante = "";
        }

    }//GEN-LAST:event_jButtonMultiplicacaoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        montante = montante + 6;
        lblResultado.setText(montante);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        montante = montante + 1;
        lblResultado.setText(montante);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        montante = montante + 2;
        lblResultado.setText(montante);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        montante = montante + 3;
        lblResultado.setText(montante);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        montante = montante + 4;
        lblResultado.setText(montante);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        montante = montante + 5;
        lblResultado.setText(montante);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        montante = montante + 7;
        lblResultado.setText(montante);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        montante = montante + 8;
        lblResultado.setText(montante);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        montante = montante + 9;
        lblResultado.setText(montante);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZeroActionPerformed
        montante = montante + 0;
        lblResultado.setText(montante);
    }//GEN-LAST:event_jButtonZeroActionPerformed

    private void jButtonBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackspaceActionPerformed
        String nova = montante.substring(0, montante.length() - 1);
        montante = nova;
        lblResultado.setText(montante);
    }//GEN-LAST:event_jButtonBackspaceActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        lblResultado.setText("0");
        montante = "";
        valor1 = 0;
        total = 0;
        ponto = 0;
        lblMontante.setText("");

    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomaActionPerformed
        if (!lblResultado.getText().equals("0")) {
            valor1 = Double.parseDouble(lblResultado.getText());
            Operacao = "+";
            lblMontante.setText(valor1 + "" + Operacao);
            lblResultado.setText("");
            montante = "";
        }


    }//GEN-LAST:event_jButtonSomaActionPerformed

    private void jButtonSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtracaoActionPerformed
        if (!lblResultado.getText().equals("0")) {

            JOptionPane.showMessageDialog(this, Clique);
            valor1 = Double.parseDouble(lblResultado.getText());
            Operacao = "-";
            lblMontante.setText(valor1 + "" + Operacao);
            lblResultado.setText("");
            montante = "";
            
        }


    }//GEN-LAST:event_jButtonSubtracaoActionPerformed

    private void jButtonDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisaoActionPerformed
        if (!lblResultado.getText().equals("0")) {
            valor1 = Double.parseDouble(lblResultado.getText());
            Operacao = "/";
            lblMontante.setText(valor1 + "" + Operacao);
            lblResultado.setText("");
            montante = "";
        }

    }//GEN-LAST:event_jButtonDivisaoActionPerformed

    private void jButtonPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPorcentagemActionPerformed
        if (!lblResultado.getText().equals("0")) {
            valor1 = Double.parseDouble(lblResultado.getText());
            Operacao = "%";
            lblMontante.setText(valor1 + "" + Operacao);
            lblResultado.setText("");
            montante = "";
        }

    }//GEN-LAST:event_jButtonPorcentagemActionPerformed

    private void jButtonVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVirgulaActionPerformed
        if (lblResultado.getText().equals("0") || lblResultado.getText().equals("")) {
            montante = "0.";
            lblResultado.setText(montante);
        } else {
            if (!existeponto(montante)) {
                montante = montante + ".";
            }
            lblResultado.setText(montante);

        }
        ponto = 1;

    }//GEN-LAST:event_jButtonVirgulaActionPerformed

    private void jButtonAlterarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarValorActionPerformed
        Double num;

        montante = lblResultado.getText();
        if (montante.length() > 0) {
            num = (-1) * Double.parseDouble(montante);
            lblResultado.setText(num.toString());
        }
    }//GEN-LAST:event_jButtonAlterarValorActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed

        String resultado;
        valor2 = Double.parseDouble(lblResultado.getText());

        if (ponto == 0) {
            if (valor2 != 0) {
                resultado = calculadora(valor1, valor2, Operacao).replace(".0", "");
                lblResultado.setText(resultado);

                lblMontante.setText("");

            }
        } else {
            if (valor2 != 0) {
                resultado = calculadora(valor1, valor2, Operacao);
                lblResultado.setText(resultado);

                lblMontante.setText("");
            }

        }
    }//GEN-LAST:event_jButtonIgualActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        Memoria = lblResultado.getText();
        lblMemoria.setText("M");

    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        lblMemoria.setText("");
        Memoria = "0";
    }//GEN-LAST:event_jButton25ActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        frmHome.contador = 20;
        contador = 10;        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        timer.stop();
        frmHome.contador = 10;
       
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        timer.start();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened
    int contador = 10;

    public void escreva() {
        System.out.println(contador);

    }
    private javax.swing.Timer timer = new javax.swing.Timer(60 * 1000, new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent e) {
            escreva();
            contador--;
            if (contador == 0) {
                timer.stop();
                dispose();
            }
        }
    });

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Display;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAlterarValor;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonBackspace;
    private javax.swing.JButton jButtonDivisao;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonMultiplicacao;
    private javax.swing.JButton jButtonPorcentagem;
    private javax.swing.JButton jButtonSoma;
    private javax.swing.JButton jButtonSubtracao;
    private javax.swing.JButton jButtonVirgula;
    private javax.swing.JButton jButtonZero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMemoria;
    private javax.swing.JLabel lblMontante;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
String montante = "";
    double valor1;
    double valor2;
    double total;
    String Operacao;
    String Memoria;
    int ponto;

    public static boolean existeponto(String ponto) {
        boolean resultado;
        resultado = false;

        for (int i = 0; i < ponto.length(); i++) {
            if (ponto.substring(i, i + 1).equals(".")) {
                resultado = true;
                break;
            }

        }
        return resultado;

    }

    public static String calculadora(double memoria1, double memoria2, String Operacao) {
        Double resultado = 0.0;
        String resposta;

        if (Operacao.equals("-")) {
            resultado = memoria1 - memoria2;

        }
        if (Operacao.equals("+")) {
            resultado = memoria1 + memoria2;

        }
        if (Operacao.equals("*")) {
            resultado = memoria1 * memoria2;

        }
        if (Operacao.equals("/")) {
            resultado = memoria1 / memoria2;

        }
        if (Operacao.equals("%")) {
            resultado = memoria1 * (memoria2 / 100);

        }

        resposta = resultado.toString();
        return resposta;
    }

}
