/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.ModeloTabelas;
import java.util.Date;
import giovanellis.SqlServer;
import java.awt.Color;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import Controlador.ControladorLancamentoDespesas;
import Modelo.ModeloLancamentoDespesas;
import java.util.Calendar;
import Modelo.teclasPermitidas;
import java.text.NumberFormat;
import Modelo.LimitadorMoeda;
import java.text.ParseException;

/**
 *
 * @author Alex
 */
public class frmDespesas extends javax.swing.JFrame {

    LimitadorMoeda limitadormoeda;
    teclasPermitidas teclaspermitidas;
    private ControladorLancamentoDespesas DAO;
    private ModeloLancamentoDespesas ObjLancaDespesa;
    private ModeloLancamentoDespesas ObjAlteraDespesa;
    SqlServer conecta;
    SqlServer connCombo;
    SqlServer conn;
    frmCalculadora calculadora;
    NumberFormat z;
    SimpleDateFormat fmt;

    public frmDespesas() throws Exception {
        fmt = new SimpleDateFormat("dd/MM/yyyy");
        limitadormoeda = new LimitadorMoeda();
        calculadora = new frmCalculadora();
        teclaspermitidas = new teclasPermitidas();
        conn = new SqlServer();
        ObjLancaDespesa = new ModeloLancamentoDespesas();
        ObjAlteraDespesa = new ModeloLancamentoDespesas();
        DAO = new ControladorLancamentoDespesas();
        conecta = new SqlServer();
        connCombo = new SqlServer();
        Color Fundo = new Color(238, 235, 227);
        getContentPane().setBackground(Fundo);
        setAlwaysOnTop(true);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagens/Icone.png")).getImage());
        initComponents();
        conecta.getCon();
        connCombo.getCon();
        z = NumberFormat.getCurrencyInstance();
        btnAlterar.setVisible(false);
        JdcPagamento.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JdcVencimento = new com.toedter.calendar.JDateChooser();
        JdcFim = new com.toedter.calendar.JDateChooser();
        JdcInicio = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableDespesas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BtnLancar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JdcPagamento = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        TxtValor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CmbDespesa = new javax.swing.JComboBox();
        jcbLancamentoDespesa = new javax.swing.JComboBox();
        txtCodDesp = new javax.swing.JTextField();
        btnCalculadora = new javax.swing.JButton();
        lblNomeDespesa = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Despesas");
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(88, 55, 66));
        jLabel1.setText("Nome da Despesa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 113, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(88, 55, 66));
        jLabel2.setText("Data de Vencimento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 235, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(88, 55, 66));
        jLabel6.setText("Valor da Despesa");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 154, -1, -1));

        JdcVencimento.setOpaque(false);
        JdcVencimento.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JdcVencimentoPropertyChange(evt);
            }
        });
        getContentPane().add(JdcVencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 150, -1));

        JdcFim.setOpaque(false);
        JdcFim.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JdcFimPropertyChange(evt);
            }
        });
        getContentPane().add(JdcFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 140, -1));

        JdcInicio.setOpaque(false);
        JdcInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JdcInicioPropertyChange(evt);
            }
        });
        getContentPane().add(JdcInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 140, -1));

        JTableDespesas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JTableDespesas.setForeground(new java.awt.Color(88, 55, 66));
        JTableDespesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTableDespesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableDespesasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableDespesas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 560, 106));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(239, 111, 83));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/button.png"))); // NOI18N
        jButton1.setText("Voltar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 100, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(239, 111, 83));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/button.png"))); // NOI18N
        jButton2.setText("Calcular");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, 100, 40));

        BtnLancar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnLancar.setForeground(new java.awt.Color(239, 111, 83));
        BtnLancar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/button.png"))); // NOI18N
        BtnLancar.setText("Lançar");
        BtnLancar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnLancar.setOpaque(false);
        BtnLancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLancarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 100, 40));

        jLabel8.setBackground(new java.awt.Color(88, 55, 66));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(239, 111, 83));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Consulta de Lançamento de Despesas");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 590, 40));

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(88, 55, 66));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("Total");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 580, -1));

        jLabel5.setBackground(new java.awt.Color(88, 55, 66));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(239, 111, 83));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Lançamentos de Despesas");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -8, 590, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(88, 55, 66));
        jLabel3.setText("Data de Pagamento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 195, -1, -1));

        JdcPagamento.setOpaque(false);
        JdcPagamento.setRequestFocusEnabled(false);
        JdcPagamento.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JdcPagamentoPropertyChange(evt);
            }
        });
        getContentPane().add(JdcPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(239, 111, 83));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/button.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 100, 40));
        getContentPane().add(TxtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(88, 55, 66));
        jLabel4.setText("Codigo da Despesa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 74, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(88, 55, 66));
        jLabel7.setText("Data Final");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 405, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(88, 55, 66));
        jLabel9.setText("Data Inicial");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 405, -1, -1));

        CmbDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbDespesaActionPerformed(evt);
            }
        });
        getContentPane().add(CmbDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 240, -1));

        jcbLancamentoDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLancamentoDespesaActionPerformed(evt);
            }
        });
        getContentPane().add(jcbLancamentoDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 170, -1));

        txtCodDesp.setEditable(false);
        getContentPane().add(txtCodDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 50, -1));

        btnCalculadora.setBackground(new java.awt.Color(88, 55, 66));
        btnCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CalculadoraIcone cópia.png"))); // NOI18N
        btnCalculadora.setOpaque(false);
        btnCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculadoraActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 50, 60));

        lblNomeDespesa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNomeDespesa.setForeground(new java.awt.Color(88, 55, 66));
        getContentPane().add(lblNomeDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 170, 20));

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(239, 111, 83));
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/button.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlterar.setOpaque(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 100, 40));

        jMenu1.setForeground(new java.awt.Color(88, 55, 66));
        jMenu1.setText("Cadastrar Despesa");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(587, 746));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        timer.stop();
        frmHome.binario = 0;
        dispose();
        calculadora.dispose();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnLancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLancarActionPerformed
        if (jcbLancamentoDespesa.getSelectedIndex()!=0)
        {
        if (validarCampos()) {
            if (preencheObjeto()) {
                try {
                    DAO.Incluir(ObjLancaDespesa);

                    JOptionPane.showMessageDialog(this, "Dados Inseridos com sucesso");

                    preencherTabela("select td.codTipoDespesa, td.NomeDespesa, td.SituacaoDespesa, d.ValorDespesa, d.DataPagamento,d.codDespesa, d.DataVencimento from Despesa as D inner join TipoDespesa as"
                            + " TD on td.codTipoDespesa = D.TipoDespesa and td.NomeDespesa = '" + NomeDespesa + "'");

                    preencherCombo();
                    double x = 0.0;
                    for (int y = 0; y < JTableDespesas.getRowCount(); y++) {
                        x += Double.parseDouble(JTableDespesas.getModel().getValueAt(y, 3).toString().replace("R$", "").replace(".", "").replace(",", "."));
                    }
                    lblTotal.setText(z.format(x));

                    limparCampos();

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao Lançar dados: " + ex);
                }
            }
        }
        }else
        {
        JOptionPane.showMessageDialog(this, "Selecione uma despesa a ser lançada");
        
        }


    }//GEN-LAST:event_BtnLancarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (CmbDespesa.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma Despesa");
        } else if (ValidaDatas()) {

            if (CmbDespesa.getSelectedIndex() == 1) {
                preencherTabela("select td.codTipoDespesa, td.NomeDespesa, td.SituacaoDespesa, d.ValorDespesa, d.DataPagamento, d.DataVencimento, d.codDespesa from Despesa as D inner join TipoDespesa as TD"
                        + " on td.codTipoDespesa = D.TipoDespesa and d.DataVencimento between '" + datainicio + "' and '" + datafim + "'");
            } else {
                Despesa = (String) CmbDespesa.getSelectedItem().toString().substring(53).replace("</span></html>", "");
                try {
                    conecta.executaSql("select * from TipoDespesa where NomeDespesa like '" + Despesa + "'");
                    conecta.rs.first();
                    CodigoDespesa = (conecta.rs.getString("codTipoDespesa"));

                } catch (SQLException ex) {
                    Logger.getLogger(frmDespesas.class.getName()).log(Level.SEVERE, null, ex);
                }

                preencherTabela("select td.codTipoDespesa, td.NomeDespesa, td.SituacaoDespesa, d.ValorDespesa, d.DataPagamento, d.DataVencimento, d.codDespesa from TipoDespesa as Td inner join Despesa as D on "
                        + "D.TipoDespesa = Td.codTipoDespesa and td.codTipoDespesa = " + CodigoDespesa + " and d.DataVencimento between '" + datainicio + "' and '" + datafim + "' order by td.NomeDespesa desc");
            }

            double x = 0.0;
            for (int y = 0; y < JTableDespesas.getRowCount(); y++) {
                x += Double.parseDouble(JTableDespesas.getModel().getValueAt(y, 3).toString().replace("R$", "").replace(".", "").replace(",", "."));
            }
            lblTotal.setText(z.format(x));

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        try {
            new frmCadastrarDespesa().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(frmDespesas.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void JTableDespesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableDespesasMouseClicked
        if (frmHome.CodPermFun == 1) {
            BtnLancar.setVisible(false);
            btnAlterar.setVisible(true);
            HabilitaCampos();
            jcbLancamentoDespesa.setVisible(false);
            lblNomeDespesa.setVisible(true);
            TxtValor.setText(null);
            int linha_selecionada = JTableDespesas.getSelectedRow(); // Pega a linha selecionada.
            txtCodDesp.setText(JTableDespesas.getValueAt(linha_selecionada, 6).toString());
            lblNomeDespesa.setText(JTableDespesas.getValueAt(linha_selecionada, 1).toString());

            try {
                JdcPagamento.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(JTableDespesas.getValueAt(linha_selecionada, 4).toString()));
            } catch (ParseException ex) {
                Logger.getLogger(frmAnotacoes.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                JdcVencimento.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(JTableDespesas.getValueAt(linha_selecionada, 5).toString()));
            } catch (ParseException ex) {
                Logger.getLogger(frmAnotacoes.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_JTableDespesasMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Color Roxo = new Color(88, 55, 66);
        Color Laranja = new Color(242, 184, 171);
        JTableDespesas.setSelectionBackground(Roxo);
        JTableDespesas.setSelectionForeground(Laranja);
        desabilitaCampos();
        preencherCombo();
        txtCodDesp.setEnabled(false);
        timer.start();
        preencherComboLancar();
        TxtValor.setDocument(new teclasPermitidas());

        TxtValor.setDocument(new LimitadorMoeda());
    }//GEN-LAST:event_formWindowOpened

    private void JdcInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JdcInicioPropertyChange
        try {
            data1 = JdcInicio.getDate();
            datainicio = fmt.format(data(JdcInicio.getDate()));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_JdcInicioPropertyChange

    private void JdcFimPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JdcFimPropertyChange
        try {
            data2 = JdcFim.getDate();
            datafim = fmt.format(data(JdcFim.getDate()));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_JdcFimPropertyChange

    private void CmbDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbDespesaActionPerformed


    }//GEN-LAST:event_CmbDespesaActionPerformed

    private void jcbLancamentoDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLancamentoDespesaActionPerformed
        NomeDespesa = (String) jcbLancamentoDespesa.getSelectedItem().toString().substring(53).replace("</span></html>", "");

        if (jcbLancamentoDespesa.getSelectedIndex() != 0) {

            HabilitaCampos();

            conecta.executaSql("select * from TipoDespesa where NomeDespesa = '" + NomeDespesa + "'");
            try {
                conecta.rs.first();
                txtCodDesp.setText(conecta.rs.getString("codTipoDespesa"));

            } catch (SQLException ex) {
                Logger.getLogger(frmDespesas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jcbLancamentoDespesaActionPerformed

    private void JdcVencimentoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JdcVencimentoPropertyChange


    }//GEN-LAST:event_JdcVencimentoPropertyChange

    private void JdcPagamentoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JdcPagamentoPropertyChange


    }//GEN-LAST:event_JdcPagamentoPropertyChange

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        frmHome.contador = 20;
        contador = 10;          // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        timer.stop();
        frmHome.contador = 10;
        frmHome.binario = 0;
        calculadora.dispose();

    }//GEN-LAST:event_formWindowClosing

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        preencherCombo();
        desabilitaCampos();
        limparCampos();
        btnAlterar.setVisible(false);
        BtnLancar.setVisible(true);
        jcbLancamentoDespesa.setVisible(true);
        lblNomeDespesa.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculadoraActionPerformed

        calculadora.setVisible(true);
        calculadora.setAlwaysOnTop(true);

    }//GEN-LAST:event_btnCalculadoraActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        if (ValidaCamposAlterar()) {
            if (preencherObjetoAlterar()) {
                try {
                    DAO.Alterar(ObjAlteraDespesa);

                    JOptionPane.showMessageDialog(this, "Dados Alterados com sucesso");

                    preencherTabela("select td.codTipoDespesa, td.NomeDespesa, td.SituacaoDespesa, d.ValorDespesa, d.DataPagamento, d.DataVencimento, d.codDespesa from Despesa as D inner join TipoDespesa as"
                            + " TD on td.codTipoDespesa = D.TipoDespesa and NomeDespesa = '" + lblNomeDespesa.getText() + "'");

                    preencherCombo();
                    desabilitaCampos();
                    limparCampos();
                    btnAlterar.setVisible(false);
                    BtnLancar.setVisible(true);
                    jcbLancamentoDespesa.setVisible(true);
                    lblNomeDespesa.setVisible(false);

                    double x = 0.0;
                    for (int y = 0; y < JTableDespesas.getRowCount(); y++) {
                        x += Double.parseDouble(JTableDespesas.getModel().getValueAt(y, 3).toString().replace("R$", "").replace(".", "").replace(",", "."));
                    }
                    lblTotal.setText(z.format(x));

                    limparCampos();

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao Alterar dados: ");
                }
            }
        }

    }//GEN-LAST:event_btnAlterarActionPerformed
    int contador = 10;

    public void escreva() {
        System.out.println(contador);

    }

    private javax.swing.Timer timer = new javax.swing.Timer(60 * 1000, new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent e) {
            escreva();
            contador--;
            if (contador == 0) {

                try {
                    dispose();
                    timer.stop();
                } catch (Exception ex) {
                    Logger.getLogger(frmInsumos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    });

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmDespesas().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(frmDespesas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLancar;
    private javax.swing.JComboBox CmbDespesa;
    private javax.swing.JTable JTableDespesas;
    private com.toedter.calendar.JDateChooser JdcFim;
    private com.toedter.calendar.JDateChooser JdcInicio;
    private com.toedter.calendar.JDateChooser JdcPagamento;
    private com.toedter.calendar.JDateChooser JdcVencimento;
    private javax.swing.JTextField TxtValor;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCalculadora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcbLancamentoDespesa;
    private javax.swing.JLabel lblNomeDespesa;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtCodDesp;
    // End of variables declaration//GEN-END:variables

    String CodigoDespesa;

    Date data1, data2, data3, data4;
    String datainicio, datafim, data, Despesa, LancDesp, DataPag, DataVenc, NomeDespesa;

    public boolean preencheObjeto() {

        int ano = JdcPagamento.getCalendar().get(Calendar.YEAR);
        int mes = JdcPagamento.getCalendar().get(Calendar.MONTH) + 1;
        int dia = JdcPagamento.getCalendar().get(Calendar.DAY_OF_MONTH);
        String DataPag = ano + "-" + mes + "-" + dia;

        int ano1 = JdcVencimento.getCalendar().get(Calendar.YEAR);
        int mes1 = JdcVencimento.getCalendar().get(Calendar.MONTH) + 1;
        int dia1 = JdcVencimento.getCalendar().get(Calendar.DAY_OF_MONTH);
        String DataVenc = ano1 + "-" + mes1 + "-" + dia1;

        ObjLancaDespesa.setCodigo(Integer.parseInt(txtCodDesp.getText()));
        ObjLancaDespesa.setValor(Double.parseDouble(TxtValor.getText().replace(".", "").replace(",", ".")));
        ObjLancaDespesa.setDataPagamento(DataPag);
        ObjLancaDespesa.setDataVencimento(DataVenc);

        return true;
    }

    public boolean preencherObjetoAlterar() {

        int ano = JdcPagamento.getCalendar().get(Calendar.YEAR);
        int mes = JdcPagamento.getCalendar().get(Calendar.MONTH) + 1;
        int dia = JdcPagamento.getCalendar().get(Calendar.DAY_OF_MONTH);
        String DataPag = ano + "-" + mes + "-" + dia;

        int ano1 = JdcVencimento.getCalendar().get(Calendar.YEAR);
        int mes1 = JdcVencimento.getCalendar().get(Calendar.MONTH) + 1;
        int dia1 = JdcVencimento.getCalendar().get(Calendar.DAY_OF_MONTH);
        String DataVenc = ano1 + "-" + mes1 + "-" + dia1;

        ObjAlteraDespesa.setCodigo(Integer.parseInt(txtCodDesp.getText()));
        ObjAlteraDespesa.setValor(Double.parseDouble(TxtValor.getText().replace(".", "").replace(",", ".")));
        ObjAlteraDespesa.setDataPagamento(DataPag);
        ObjAlteraDespesa.setDataVencimento(DataVenc);

        return true;
    }

    public Date datas(Date i) {

        datainicio = fmt.format(i);
        DateFormat df = DateFormat.getDateInstance(DateFormat.LONG, new Locale("pt", "BR"));

        return i;

    }

    public Date data(Date f) {

        datafim = fmt.format(f);
        DateFormat df = DateFormat.getDateInstance(DateFormat.LONG, new Locale("pt", "BR"));

        return f;

    }

    public boolean validarCampos() {
        if (TxtValor.getText().equals("") || TxtValor.getText().equals("0,00")) {
            JOptionPane.showMessageDialog(this, "Informe o valor da despesa");
            TxtValor.requestFocus();
            return false;
        }
        if (TxtValor.getText().length() > 8) {
            JOptionPane.showMessageDialog(this, "Salário Superior ao Permitido");
            return false;
        }
        try {
            if (JdcVencimento.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Informe a data de Vencimento");
                JdcVencimento.requestFocus();
                return false;
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Informe a Data de Vencimento");
        }

        try {
            if (JdcPagamento.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Informe a data de Pagamento");
                JdcPagamento.requestFocus();
                return false;
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Informe a Data de Pagamento");
        }

        return true;

    }

    public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{
            "<html><span style='color:#ef6f53;font-weight: bold;'>Código</span></html>",
            "<html><span style='color:#ef6f53;font-weight: bold;'>Nome da Despesa</span></html>",
            "<html><span style='color:#ef6f53;font-weight: bold;'>Situação</span></html>",
            "<html><span style='color:#ef6f53;font-weight: bold;'>Valor</span></html>",
            "<html><span style='color:#ef6f53;font-weight: bold;'>Pagamento</span></html>",
            "<html><span style='color:#ef6f53;font-weight: bold;'>Vencimento</span></html>",
            "<html><span style='color:#ef6f53;font-weight: bold;'>codDespesa</span></html>"
        };

        NumberFormat z = NumberFormat.getCurrencyInstance();
        conecta.executaSql(Sql);
        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("codTipoDespesa"), conecta.rs.getString("NomeDespesa"), conecta.rs.getString("SituacaoDespesa"), z.format(conecta.rs.getDouble("ValorDespesa")), fmt.format(conecta.rs.getDate("DataPagamento")), fmt.format(conecta.rs.getDate("DataVencimento")), conecta.rs.getInt("codDespesa")});
            } while (conecta.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao preencher a Tabela");

        }

        ModeloTabelas modelo = new ModeloTabelas(dados, Colunas); //Instacia a classe do modelo da Tabela.
        JTableDespesas.setModel(modelo);
        JTableDespesas.getColumnModel().getColumn(0).setPreferredWidth(50); // Tamanho em pixel da coluna
        JTableDespesas.getColumnModel().getColumn(0).setResizable(false);
        JTableDespesas.getColumnModel().getColumn(1).setPreferredWidth(143);
        JTableDespesas.getColumnModel().getColumn(1).setResizable(false);
        JTableDespesas.getColumnModel().getColumn(2).setPreferredWidth(60);
        JTableDespesas.getColumnModel().getColumn(2).setResizable(false);
        JTableDespesas.getColumnModel().getColumn(3).setPreferredWidth(120);
        JTableDespesas.getColumnModel().getColumn(3).setResizable(false);
        JTableDespesas.getColumnModel().getColumn(4).setPreferredWidth(90);
        JTableDespesas.getColumnModel().getColumn(4).setResizable(false);
        JTableDespesas.getColumnModel().getColumn(5).setPreferredWidth(90);
        JTableDespesas.getColumnModel().getColumn(5).setResizable(false);

        JTableDespesas.getColumnModel().getColumn(6).setMaxWidth(0);
        JTableDespesas.getColumnModel().getColumn(6).setMinWidth(0);
        JTableDespesas.getTableHeader().getColumnModel().getColumn(6).setMaxWidth(0);
        JTableDespesas.getTableHeader().getColumnModel().getColumn(6).setMinWidth(0);
        JTableDespesas.getTableHeader().setReorderingAllowed(false);
        JTableDespesas.setAutoResizeMode(JTableDespesas.AUTO_RESIZE_OFF);//Não pode ser redimensionada
        JTableDespesas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    public void preencherCombo() {

        connCombo.getCon();
        connCombo.executaSql("select distinct NomeDespesa from TipoDespesa as Td inner join Despesa as D on D.TipoDespesa = Td.codTipoDespesa order by NomeDespesa");

        try {

            CmbDespesa.removeAllItems();
            connCombo.rs.first();
            CmbDespesa.addItem("<html><span style='color:#583742;font-weight: bold;'>Selecione a Despesa...</span></html>");
            CmbDespesa.addItem("<html><span style='color:#583742;font-weight: bold;'>Todas</span></html>");

            do {
                CmbDespesa.addItem("<html><span style='color:#583742;font-weight: bold;'>" + (connCombo.rs.getString("NomeDespesa") + "</span></html>"));

            } while (connCombo.rs.next());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ComboBox");
        }
    }

    public void preencherComboLancar() {
        connCombo.getCon();
        connCombo.executaSql("select NomeDespesa from TipoDespesa where SituacaoDespesa = 'Ativo' order by NomeDespesa");

        try {
            connCombo.rs.first();
            jcbLancamentoDespesa.addItem("<html><span style='color:#583742;font-weight: bold;'>Selecione a Despesa...</span></html>");
            do {

                jcbLancamentoDespesa.addItem("<html><span style='color:#583742;font-weight: bold;'>" + (connCombo.rs.getString("NomeDespesa") + "</span></html>"));

            } while (connCombo.rs.next());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ComboBox");
        }
    }

    public boolean ValidaDatas() {
        try {

            if ((data1.getDate() - data2.getDate()) > 0) {
                JOptionPane.showMessageDialog(this, "Data inicial maior que a data final, ou data final menor que a inicial");
                return false;
            }

        } catch (Exception e) {
        }

        if (JdcInicio.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Informe a data Inicial");

            return false;
        }
        if (JdcFim.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Informe a data Final");

            return false;
        }

        return true;

    }

    public void desabilitaCampos() {
        TxtValor.setEnabled(false);
        JdcPagamento.setEnabled(false);
        JdcVencimento.setEnabled(false);
        BtnLancar.setEnabled(true);
    }

    public void HabilitaCampos() {
        TxtValor.setEnabled(true);
        JdcPagamento.setEnabled(true);
        JdcVencimento.setEnabled(true);
        BtnLancar.setEnabled(true);
    }

    public void limparCampos() {
        TxtValor.setText("");
        JdcPagamento.setDate(null);
        JdcVencimento.setDate(null);
        jcbLancamentoDespesa.setSelectedIndex(0);
        txtCodDesp.setText("");
    }

    public boolean ValidaCamposAlterar() {

        if (JdcPagamento.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Informe a Data de Pamento");

            return false;
        }
        if (JdcVencimento.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Informe a Data de Vencimento");

            return false;
        }

        if (TxtValor.getText().equals("") || TxtValor.getText().equals("0,00")) {
            JOptionPane.showMessageDialog(this, "Informe o valor da Despesa");
            return false;
        }

        return true;

    }

}
